### ISSUE TITLE
Parse localized housenumber (italian)

### ISSUE THREAD

**Issue by mamico** [osm-search/Nominatim#1086]
don't know if it's the same as #177...

The search `69, Via Montalti, Cesena` yields a result. (https://nominatim.openstreetmap.org/search.php?q=69%2C+Via+Montalti%2C+Cesena&polygon_geojson=1&viewbox=)

Instead with the searches `Via Montalti, 69 Cesena` or `Via Montalti, 69, Cesena` that how usally in Italy are written the addresses, there are no results. (https://nominatim.openstreetmap.org/search.php?q=Via+Montalti%2C+69+Cesena&polygon_geojson=1&viewbox=)

**Comment by lonvia** [comment]
Nominatim takes an educated guess and assumes that the housenumber either appears in the first or last part of the search query ("part"s being comma-separated here). I'm reluctant to relax this assumption because it will add a lot more permutations to the interpretations of the search, most of them wrong. `Via Montalti 69, Cesena` will work and so will `Via Montalti 69 Cesena`.

**Comment by mamico** [comment]
@lonvia thank you for your answer, nad your work. But I think I have unintentionally polluted this issue, because I added a short name "Via Montalti" to the street "Via Cesare Montalti" and after that all the searches went well, everywhere I put the house number.

So I think that, at least, the real "problem" is more like # 679 # 1093 # 828 # 753 ... feel free to close this issue.

IMHO people want a geocoder that works more like a fulltext search engine, so probably the best would be that OSM Foundation adopts a geocoder more similar to Photon and leave people the choice between Nominatim and Photon in base at the own use case.

**Comment by lonvia** [comment]
Closing this one. #679 has a more detailed discussion of the shortened street name issue.
