### ISSUE TITLE
Country terms in word table need to be cleaned regularly

### ISSUE THREAD

**Issue by teresapeteti** [osm-search/Nominatim#1342]
Hi,

A search for only "Mauritania" is returning "Mauritania" and "Senegal" in results.

![image](https://user-images.githubusercontent.com/29470703/54982127-05c37c00-4fd0-11e9-9489-c8207f292f59.png)

![image](https://user-images.githubusercontent.com/29470703/54981673-e710b580-4fce-11e9-8e4a-ce6035c91cba.png)

https://www.openstreetmap.org/search?query=Mauritania#map=8/14.475/-14.565

Thanks

**Comment by mtmail** [comment]
I see the mismatched Senegal pointing to a relation listed on https://nominatim.openstreetmap.org/deletable.php Nominatim doesn't immediately delete countries because sometimes such deletions happen by accident. I don't have access to the openstreetmap.org server myself and need to wait for an administrator to manually delete it.

**Comment by lonvia** [comment]
I've cleared the stale relation but the issue remains there. I suspect that the term has crept into the word list. I'm not sure how to best refresh that. There is no mechanism for it.

**Comment by lonvia** [comment]
I've now manually deleted the offending terms from the `word` table but that's naturally no way to solve the issue in general. We need a way to clean out the word terms for countries in the same way we do with postcodes and run this on a regular basis.
