### ISSUE TITLE
New Special Phrases - autoimport - is it possible?

### ISSUE THREAD

**Issue by mutipg** [osm-search/Nominatim#1362]
Hi, I found another old and closed thread in this subject, but I want ask for import new special phrases, which one I had added in Polish language. Some of them I had added 6 months ago.

I think, that special phrases should be importing automatically at least monthly. Is there a possibility to write any script for this? Frequently updating special phrases will be stimulating for adding new phrases in local language for users.

Instead of autoimport once more please to import Polish Special Phrases to Nominatim: Nominatim/Special_Phrases/PL

Thank you!

**Comment by mark-lester** [comment]
I'll take this next. 
I dont know if you assign this to me I can in turn assign  it to a pull request. Lets try

**Comment by lonvia** [comment]
We'd need a routine similar to the special phrase import. Instead of creating all the special phrases and tables after having read the data from the wiki, the update routine would have to:

* get the list of current phrases from the `word` table, and remove outdated entries
* add all phrases entries that are new to the `word` table
* remove all `place_classtype_*` tables that are no longer needed
* add `place_classtype_*` tables that are not yet there

**Comment by AntoJvlt** [comment]
To be sure, do we need a new command for this, like: special-phrases --update-from-wiki?

Or should it be handled by the existing special-phrases --import-from-wiki by looking for an update if needed?

**Comment by lonvia** [comment]
If `--import-from-wiki` magically does the right thing that would be perfect. But if it is easier to have an extra function then that is fine with me, too.

**Comment by AntoJvlt** [comment]
Sure, I will start working on it.

**Comment by AntoJvlt** [comment]
I am taking some time to solve this because I have a lot of other works to produce for this wenesday.

I have one question in order to not make any mistakes. I am pretty sure the word table is not only filled and used by the special phrases, how can I safely check for the current imported special phrases into it? Should I check that the operator is not null or that the class and type are not null, or checks both maybe?

**Comment by lonvia** [comment]
Indeed, that would be useful to know. It's a special phrase if class is not null except for `class=place` and `type=house`, which is a housenumber term.

Best place to look up the different types of words is in the query code where the word entries are collected: https://github.com/osm-search/Nominatim/blob/c0f0b665091dfacd29727efed5efbe111c5900bf/lib-php/TokenList.php#L109
