### ISSUE TITLE
Reranking needs to preserve order

### ISSUE THREAD

**Issue by geoneutrino** [osm-search/Nominatim#1436]
uk postcodes in combination with town/street names sometimes result in results worse than postcode alone
E.g. the address of openstreetmap foundation :)
entering only postcode
CB4 0WS
results in correct location 
https://www.openstreetmap.org/search?query=CB4%200WS#map=16/52.2324/0.1584

Entering the complete address
https://www.openstreetmap.org/search?query=Cowley%20Road%20CB4%200WS%20Cambridge#map=19/52.22795/0.15669
jumps to a segment of cowley road several hundred meters away with postcode CB4 0WU
although search loop 1 finds a result with the correct code
https://nominatim.openstreetmap.org/search.php?format=xml&addressdetails=1&q=Cowley%20Road%20CB4%200WS%20Cambridge&limit=10&debug=1

Is it possible to "boost" the priority of postcodes if given in uk addresses ?

**Comment by tbertels** [comment]
It's currently hard coded here: https://github.com/openstreetmap/Nominatim/blob/b0e6fb73c6ccabbc28464e5a9910ef7bd3293e0e/sql/functions.sql#L282

**Comment by tbertels** [comment]
Though I don't understand why [this German street](https://nominatim.openstreetmap.org/details.php?place_id=115956975) postcode gets an address rank of 5 instead of 11.

**Comment by tbertels** [comment]
> 
> 
> Though I don't understand why [this German street](https://nominatim.openstreetmap.org/details.php?place_id=115956975) postcode gets an address rank of 5 instead of 11.

It's actually because the database needs to be updated (see https://github.com/openstreetmap/Nominatim/commit/b8f7b3cc8dfe4da04bf3d4c26cf152dc0886665d#commitcomment-34839750).

About the issue itself, you want to give more weight to UK postcodes than to street names.
According to https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom a UK postcode + a house number is enough to deliver the mail, meaning that the postcode is at least as precise as the street name (and is actually more precise).
So it seems indeed a good idea. A rank_search of 28 for postcodes matching ^([A-Z][A-Z]?[0-9][0-9A-Z]? [0-9][A-Z][A-Z])$ seems reasonable. For the record, buildings numbers have a search rank of 28 and names rank 29, whereas streets rank as high as 27.

**Comment by geoneutrino** [comment]
good input, thanks
in this commit https://github.com/openstreetmap/Nominatim/commit/9228d91849abaf25d95287a21f666c7f481dc321
i found several regex for postcode formats in differnt countries but it seems this code is not yet merged to master

So if wikipedia is right with postcode + housenumber it might be a generic impprovement in nominatim to enhance result (ignore all other words) quality but i cannot say if this would cause side effects .

**Comment by lonvia** [comment]
Increasing the rank_search does not "boost" anything in this case. The problem here is a different one. Nominatim initially nicely orders the results by proximity to the postcode but then shuffles the order again during reranking. It should not do that unless the sorting criterion actually demands to revise the order.
