### ISSUE TITLE
Reverse should have a mode to look for addresses only

### ISSUE THREAD

**Issue by kevin-argus** [osm-search/Nominatim#1469]
Hi,
Some addresses come back without house_number while they are in the middle of a city.
Is there a way to add a parameter forcing house_number whenever is possible instead of the place name?
Request URL:
https://nominatim.openstreetmap.org/reverse?lat=-37.199700&lon=174.902920&format=json&zoom=30

Response:
```
{
  "place_id": 93719414,
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type": "way",
  "osm_id": 83018218,
  "lat": "-37.1995943",
  "lon": "174.902213242405",
  "display_name": "Countdown, Seddon Lane, Buckland, Franklin, Auckland, 2120, New Zealand",
  "address": {
    "supermarket": "Countdown",
    "road": "Seddon Lane",
    "suburb": "Buckland",
    "city": "Franklin",
    "state": "Auckland",
    "postcode": "2120",
    "country": "New Zealand",
    "country_code": "nz"
  },
  "boundingbox": [
    "-37.1998837",
    "-37.1992594",
    "174.9018292",
    "174.9026008"
  ]
}
```

But Google reverse geocoder test page ([link](https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse))
Returns an exact address for -37.199700,174.902920
70 Edinburgh St, Pukekohe 2120, New Zealand

Thank you so much.

**Comment by lonvia** [comment]
That's a data issue with OSM data. Reverse geocoding doesn't return the closest address but the closest OSM object. And that may or may not have the house number tagged. In that particular case the Countdown itself doesn't have a house number. There are two house numbers inside the building outline but that is information Nominatim cannot use at the moment. (And actually never will in this case because it wouldn't be clear which of the two housenumbers to use.)

**Comment by lonvia** [comment]
As this is a frequent (and not totally unreasonable ;) request, I'm thinking about allowing reverse geocoding for addresses only. Just need to think about how to best add this to the API.

**Comment by wimvr** [comment]
Above a try to fix this problem, bit different than initially requested, but more freedom to define how to look for a housenumber (does it have to be same street or not, and how far to look).

It is implementation I made because I couldn't wait for Nominatim to pick up, if it fits in the structure I don't know. I'm not an expert in the data model, so no guarantees this is the best solution. For me it gives better results.

**Comment by saffer001** [comment]
Any news on this issue? I see it's still open and it's been 4 years?

**Comment by lonvia** [comment]
This is now implemented with the new [layer parameter](https://nominatim.org/release-docs/develop/api/Reverse/#result-restriction). This works for reverse and search.

Example: https://nominatim.openstreetmap.org/reverse?lat=-37.199700&lon=174.902920&format=json&zoom=30&layer=address
