### ISSUE TITLE
Wrong result for Russian city Ufa

### ISSUE THREAD

**Issue by danielsbv** [osm-search/Nominatim#1632]
Submitting the name of the city in Russia Уфа (Ufa) service returns results "UEFA, 46, Route de Genève, Village des Pêcheurs, Nyon, 1260, Switzerland" which is not Ufa nor even Russia

**Comment by lonvia** [comment]
A classic case of wikipedia tag mayhem. The UEFA headquarter building got associated with the wikipedia page for UEFA and inherits thus the importance of the association.

I've removed the wikipedia entry from Nominatim's database but I think that is not really a sustainable fix. The building tagging really isn't optimal and needs to change. Some suggestions: the name should likely be more something along the lines of 'UEFA headquarters' because 'UEFA' is an association not a building. The wikipedia tag may not be the best either as the article is not about the building. 'operator:wikipedia' maybe?

**Comment by lonvia** [comment]
This resolved itself with stricter transliteration. UEFA and UFA no longer transliterate to the same term.
