### ISSUE TITLE
City missing from reverse geocoding results even though it is present in `display_name`

### ISSUE THREAD

**Issue by maratumba** [osm-search/Nominatim#1736]
https://open.mapquestapi.com/nominatim/v1/reverse.php?lon=27.557909&lat=41.826981&format=jsonv2&key=[KEY]

I reported the same to mapquest but I thought I should report it here too. Feel free to delete the issue if this is the wrong place.

The above query returns the data below. The name of the city is 'Kırklareli', which is present in the `display_name` but not within `address`. 

The result is the same with XML format.

result: 
```json
{
"place_id":"141921752",
"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright",
"osm_type":"way",
"osm_id":"303422728",
"lat":"41.8563433",
"lon":"27.568878",
"place_rank":"26",
"category":"highway",
"type":"tertiary",
"importance":"0.1",
"addresstype":"road",
"display_name":"Sarpdere, Demirköy, Kırklareli, Marmara Region, Turkey",
"name":null,
"address":
 {
    "village":"Sarpdere",
    "county":"Demirköy",
    "state":"Marmara Region",
    "country":"Turkey",
    "country_code":"tr"
},
"boundingbox":["41.8389783","41.8683025","27.5585022","27.5842118"]
}
```

**Comment by lonvia** [comment]
'Kirklareli' is not a city here. It refers to the [province of Kirklareli](https://www.openstreetmap.org/relation/223469). (The coordinate you requested is [in the middle of nowhere](https://nominatim.openstreetmap.org/reverse.php?lon=27.557909&lat=41.826981&format=html)). Kirklareli province doesn't show because 'Marmara Region' and 'Kirklareli' both translate to a 'state', so only one of them can show up in the address list. Looking at the code, there is no real reason why the two should be conflated. I think we can fix that.

**Comment by lonvia** [comment]
The parts now show nicely on [nominatim.openstreetmap.org](https://nominatim.openstreetmap.org/reverse.php?lon=27.557909&lat=41.826981&format=jsonv2). Unfortunately, this will help nothing with MapQuest. They run a very, very old version of the software.
