### ISSUE TITLE
Reverse geolocator gives inaccurate way id for a link

### ISSUE THREAD

**Issue by thevooght** [osm-search/Nominatim#1747]
I'm use the Naminatim geolocator reverse and I'm trying to get a way id giving a location (latitude,longitude).
When giving a location on a motorway_link it returns the way id of the highway where it's leading to or where it's coming from.
This is my code:
geolocator = Nominatim(user_agent="sunglare_app")
position = (lat, lon)
location = geolocator.reverse(position)

Tested on location: 
lat=51.19406
lon=3.78330

Returned:
{'place_id': 164934950,
 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
 'osm_type': 'way',
 'osm_id': 333482261,
 'lat': '51.19477370315226',
 'lon': '3.7834330598379444',
 'display_name': 'E34, De Katte, Zelzate, Oost-Vlaanderen, Vlaanderen, 9060, België - Belgique - Belgien',
 'address': {'road': 'E34',
  'neighbourhood': 'De Katte',
  'town': 'Zelzate',
  'county': 'Oost-Vlaanderen',
  'state': 'Vlaanderen',
  'postcode': '9060',
  'country': 'België - Belgique - Belgien',
  'country_code': 'be'},
 'boundingbox': ['51.1943121', '51.1950631', '3.7818808', '3.7859592']}

So the osm_id returned was 333482261, but 25461466 was expected.
Thanks for your help

**Comment by lonvia** [comment]
Link roads are only included in Nominatim when they have a name. That's because the main purpose for `nomiatim.openstreetmap.org` is searching and they are not needed for that when they don't have a name.

You can easily include the link roads in your own installation of Nominatim. Simply adapt the import style. In the [highway section](https://github.com/osm-search/Nominatim/blob/master/settings/import-street.style#L78) simply remove the lines with '*link' and these roads will be included unconditionally.

**Comment by thevooght** [comment]
Thanks a lot!
