### ISSUE TITLE
No results for search 'Kahl'

### ISSUE THREAD

**Issue by git-tgo** [osm-search/Nominatim#1755]
See title, and search-link:
https://nominatim.openstreetmap.org/search.php?q=Kahl&polygon_geojson=1&viewbox=
says: _"No search results found"_
https://www.openstreetmap.org/search?query=Kahl#map=0/7/87
says: _"Keine Ergebnisse gefunden"_

I would expect result like the river:
https://en.wikipedia.org/wiki/Kahl_(river)
Found in osm: https://www.openstreetmap.org/relation/4860439 or involved way (https://www.openstreetmap.org/way/25851038)
or even the result of a municipality:
https://en.wikipedia.org/wiki/Kahl_am_Main
Found in osm: https://www.openstreetmap.org/relation/534299 or involved admin_centre-node (https://www.openstreetmap.org/node/240100441)

Is it probably necessary to change any osm-data to get some nominatim results, or is it necessary to change any part of the search engine algorithm?

Thanks in advance for checking.

**Comment by lonvia** [comment]
This is a fallout of the recently fixed #722. The database just hadn't caught up yet. I've cleaned out all the waterways in the database now and the river relation shows up as expected. See #722 for a detailed explanation why no result at all showed up.

(Side note: it also finds https://www.openstreetmap.org/way/438983977 because it is missing as a member in the river relation. Something to fix.)

**Comment by git-tgo** [comment]
Thanks for instant fixing and explantions :-)
