### ISSUE TITLE
Data has changed - no state available in Hamburg anymore

### ISSUE THREAD

**Issue by FabianL1** [osm-search/Nominatim#1759]
I'am not sure what has changed but using this query:
https://nominatim.openstreetmap.org/search?postalcode=21075&format=json&addressdetails=1&country=Deutschland&accept-language=de&city=Ei%C3%9Fendorf

I previously received:

suburb: "Heimfeld",
city_district: "Harburg",
city: "Hamburg",
state: "Hamburg",
postcode: "21075",
country: "Deutschland",
country_code: "de",

Now I receive:

suburb: "Eißendorf",
city_district: "Harburg",
city: "Hamburg",
country: "Deutschland",
country_code: "de"

Without state - which breaks huge parts of my application. Why is this? :)

**Comment by lonvia** [comment]
This was an intentional change. Hamburg is a "city state" and it's not possible to return it in the "city" field and the "state" field without adding a lot of special casing. That it came out with both until now was just a coincidence and actually changed depending on the current state of the OSM data. The new behaviour is much more consistent: if there are administrative areas that span multiple levels, then only the lowest is reported. A "city state" has only "city" set, a "kreisfreie Stadt" will report a "city" and a "state" but no "county". (That's all minus the fact that the server has not yet updated all data according to the new rules and that there are some errors in the OSM data that also mess with the address computation.)

Closing as "won't fix".

**Comment by FabianL1** [comment]
Thanks a lot - can you tell me where I can sign in to get Emails about those changes? :)

**Comment by lonvia** [comment]
nominatim.openstreetmap.org always runs the latest master. It is a bit of a testing ground in that way. So for changes there, it is best to follow this repository. I try to make PRs with meaningful descriptions these days.

For releases there is always an announcement on [the geocoding mailinglist](https://lists.openstreetmap.org/listinfo/geocoding).
