### ISSUE TITLE
lat and lon for zipcode 45401 is not correct

### ISSUE THREAD

**Issue by jguo317** [osm-search/Nominatim#179]
When I use nominatim to search for the zip code 45401, it returns Brunswick, but it should be Dayton, OH. It seems this zipcode returns incorrect latitude and longitude.
The lat and lon for 45401 should be (39.750471,-84.268593), not 31.1319976, -81.4859267)

The url is http://nominatim.openstreetmap.org/search?q=45401&format=json&polygon=0&addressdetails=1&limit=3&countrycodes=us,ca.

**Comment by mtmail** [comment]
The 2017 Tiger Nominatim import hasn't fixed it. Nominatim imports it into separate database tables and during a search considers both OSM data (table) and Tiger data (table).

Turns out the issue is in OSM data, but caused by a Tiger->OSM import from 6 years ago. 5 digit numbers got imported into the `ref` tag which gets treated as name and has preference over postcode search.

It needs OSM data cleanup and check how many places are affected.

Examples:
https://www.openstreetmap.org/way/9261792#map=16/31.1418/-81.4844
https://www.openstreetmap.org/way/286996246#map=16/31.1384/-81.4848

![image](https://user-images.githubusercontent.com/3727288/36350793-5b60bb0a-149e-11e8-9944-71403cd2aa5e.png)

**Comment by mtmail** [comment]
I cleaned up 130 streets. https://www.openstreetmap.org/changeset/56459989

Next problem: Now the query returns no result. https://nominatim.openstreetmap.org/search?q=45401&format=json&polygon=0&addressdetails=1&limit=3&countrycodes=us,ca

**Comment by lonvia** [comment]
The supplemental US postcodes hadn't been updated yet on osm.org. I've done that now and the new postcodes should appear with next night's update of postcodes.
