### ISSUE TITLE
Search "campo del príncipe" does not match object "Plaza Campo del Príncipe"

### ISSUE THREAD

**Issue by daniel-callejas-sevilla** [osm-search/Nominatim#1811]
Object I'm searching: https://www.openstreetmap.org/way/161955945 (last modified 5 months ago, 
highway=tertiary+name=Plaza Campo del Príncipe).

Search criteria: 
* Starting at https://www.openstreetmap.org/#map=12/37.1893/-3.6211
* Search for "campo del príncipe": Query: https://www.openstreetmap.org/search?query=campo%20del%20pr%C3%ADncipe#map=19/19.38228/-102.03772 (query URL has moved the map to the wrong place to show bad results)

Expected:
* My object is found (or any of the other objects with same name around the same place).
* https://www.openstreetmap.org/way/161955945 or any of the connected objects with same name

Actual:
* My object is not found.
* Two results appear for unrelated search terms "Paseo del Príncipe" (missing keyword "campo", ignoring the area of the map that was focused prior to search).

System:
Linux 4.15.0-99-lowlatency / Kubuntu 18.04.4 LTS / 8 GB RAM

**Comment by lonvia** [comment]
'campo' gets shortened to 'c po' (an Italian abbreviation) and so does 'calle paseo' (Spanish abbreviations). That's why Nomatim thinks these two are the same. This is one of these cases where abbreviations from different languages lead to confusion, similar to #333. 

Eventually, we need to completely rethink abbreviation handling. This is already covered in #1208, so closing here.
