### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by toton6868** [osm-search/Nominatim#1812]
```
/opt/Nominatim/module/Makefile:11: warning: overriding recipe for target 'install'
/usr/local/lib/postgresql/pgxs/src/makefiles/pgxs.mk:241: warning: ignoring old recipe for target 'install'
make[3]: /usr/bin/clang: Command not found
/usr/local/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.global:1044: recipe for target 'nominatim.bc' failed
make[3]: *** [nominatim.bc] Error 127
module/CMakeFiles/nominatim_lib.dir/build.make:60: recipe for target '../module/dummy' failed
make[2]: *** [../module/dummy] Error 2
CMakeFiles/Makefile2:1093: recipe for target 'module/CMakeFiles/nominatim_lib.dir/all' failed
make[1]: *** [module/CMakeFiles/nominatim_lib.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mtmail** [comment]
> /usr/bin/clang: Command not found

Install clang

Please put effort into bug reports. What version you used, which operating system, which tutorial or installation guide you follow, what you've tried before you gave up.

**Comment by toton6868** [comment]
Sorry for bothering you guys. I am trying to put an effort into Nominatim after Pelias and Photon. But sorry to say, it is weird that I need to install Apache PHP and a few other libraries. Moreover, I was unable to start it with existing PostgreSQL. Can you please let me know is my `make` done properly. I got following in the terminal
```
/opt/osgs/Nominatim/module/Makefile:11: warning: overriding recipe for target 'install'
/usr/local/lib/postgresql/pgxs/src/makefiles/pgxs.mk:241: warning: ignoring old recipe for target 'install'
[100%] Built target nominatim_lib
```
After that I am using the following commands
```wget -O /PATH/TO/ROOT/osrm/Nominatim/data/country_osm_grid.sql.gz http://www.nominatim.org/data/country_grid.sql.gz
sudo -u postgres createuser www-data
sudo -u postgres psql nominatim
GRANT usage ON SCHEMA public TO "www-data";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "www-data";
sudo -su postgres./utils/setup.php --osm-file ../../data/map.osm.pbf --all 2>&1 | tee setup.log
```
It is returning no nominatim database found.
Is there any easy installation guide which can help me to build and start nominatim with existing postgresql? Sorry I am a newbie

**Comment by mtmail** [comment]
In the left-hand navigation on http://nominatim.org/release-docs/latest/ Under 'Appendix' there's two guides for Ubuntu and CentOS. The text is extracted from the scripts in https://github.com/osm-search/Nominatim/tree/master/vagrant and for new installed operating systems or virtual machines that's the best starting point.

If you're familiar with docker you can have a look at https://github.com/mediagis/nominatim-docker It's maintained by a different team.

Nominatim installation requires almost a dozen software libraries. PHP is needed because the API and much of the logic is written in PHP and Apache because the main interface is HTTP. You can skip Apache if you only want to run `./utils/query.php` on command-line.

> warning: ignoring old recipe for target 'install'

That can be ignored, all fine.

> It is returning no nominatim database found.

Should be fine, because the first step of `./utils/setup.php --all` will create it. Maybe there's a way to filter the warning, it's confusing.

With your output it should import all data now. There's `./utils/check_import_finished.php` to see if all tables and indices got created. Once one you can use `./utils/query.php` or with Apache http://localhost:8089/nominatim/search.php

**Comment by toton6868** [comment]
Thanks for the vagrant shell scripts. I was actually writing a shell script to install Nominatim within a docker. I am creating a custom docker image. I have already built PostgreSQL 12.03, PostGIS 3.0.3, Geos, Proj, Gdal. Now I just wanted to know if I skip the two lines from the vagrant script like this 
```
...
                            postgresql-server-dev-10 postgresql-10-postgis-2.4 \
                            postgresql-contrib-10 postgresql-10-postgis-scripts \
...
```
will it be a problem to build Nominatim?

**Comment by mtmail** [comment]
Most likely. The Nominatim `make` builds a postgresql extension (.so file) and needs postgresql header files. If postgresql is installed on another server (or docker container) then the .so file needs to be copied there first.
