### ISSUE TITLE
Nominatim not using Tiger data after it is installed?

### ISSUE THREAD

**Issue by collinpu** [osm-search/Nominatim#1903]
Hello, 

After following the instructions on the installation guide to install Nominatim, build the postgresdb, and add the Tiger dataset, querying most street addresses in the US still returns no result. For a sanity check, I tried querying the same street addresses against Tigerweb (https://tigerweb.geo.census.gov/tigerweb/) and they all came back as hits. Is this normal behavior or should Nominatim have the street addresses in the Tiger dataset after you've installed the Tiger dataset? I did a full planet install using the following steps: 

1.) Perform basic config setup and requirements installs from here (https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/)
2.) Download additional data sources using: 
     cd $NOMINATIM_SOURCE_DIR/data
     wget https://www.nominatim.org/data/wikimedia-importance.sql.gz
     wget https://www.nominatim.org/data/gb_postcode_data.sql.gz
     wget https://www.nominatim.org/data/us_postcode_data.sql.gz

3.) Build postgres db using ./utils/setup.php --osm-file <data file> --all --threads 16

4.) Add special phrases using: 
    ./utils/specialphrases.php --wiki-import > specialphrases.sql
    psql -d nominatim -f specialphrases.sql

5.) Finally, download and install Tiger dataset: 
    cd Nominatim/data
    wget https://nominatim.org/data/tiger2019-nominatim-preprocessed.tar.gz
    tar xf tiger2019-nominatim-preprocessed.tar.gz
    cd Nominatim/build
    ./utils/setup.php --import-tiger-data
    ### Add "@define('CONST_Use_US_Tiger_Data', true);" to /Nominatim/build/settings/local.php
    ./utils/setup.php --create-functions --enable-diff-updates --create-partition-functions

Is there anything else I need to do? Restart anything? 

My local.php: 
 // Paths
 @define('CONST_Postgresql_Version', '9.5');
 @define('CONST_Postgis_Version', '2.2');
 // Website settings
 @define('CONST_Website_BaseURL', '/');
 @define('CONST_Use_US_Tiger_Data', true);
?>
~     

Content of data/tiger folder: 
01001.sql ..... through ..... 78030.sql (there are probably a few thousand .SQL files in total, 01001.sql is the first and 78030.sql is the last)

**Comment by lonvia** [comment]
What is the size of the table `location_property_tiger`? (Run `psql -d nominatim -c 'select count(*) from location_property_tiger'`.)

Can you give examples of addresses that don't work? Do they work on https://nominatim.openstreetmap.org?

**Comment by collinpu** [comment]
Hi, 

The size of location_property_tiger is 33496424

Try this address for example: 25922 Manley Ct, Calabasas, CA 91302

It is not found on https://nominatim.openstreetmap.org or my local install, but it is found on https://tigerweb.geo.census.gov/tigerweb/

**Comment by lonvia** [comment]
That's because according to OpenStreetMap [Manley Ct](https://www.openstreetmap.org/way/13327811) is not in [Calabasas](https://www.openstreetmap.org/relation/3353286). Searching just for [25922 Manley Ct](https://nominatim.openstreetmap.org/ui/search.html?q=25922+Manley+Ct) gives you the correct result.

Importing the Tiger data does not mean that you get the Tiger addresses literally. Nominatim just takes the house numbers from the data and mixes it with the existing OSM data. That means that street, city and county data has to be correct in OpenStreetMap in order for search to work properly.

**Comment by collinpu** [comment]
That is very interesting since 25922 Manley Ct, Calabasas, CA 91302 is it's mailing address. Any idea why there is a discrepancy between a location's mailing address and its OSM address? 

BTW, I've read a ton of your answers to other questions posted over the years and I just wanted to say you're awesome. I think I speak for everyone when I say how much we appreciate your help!

**Comment by lonvia** [comment]
OSM doesn't really index mailing addresses. It creates more of a location description by checking in which administrative areas a certain place is. The reason for this is simple: you can only have mailing addresses for very specific objects (i.e. houses or plots) while Nominatim needs to be able find all objects under the sun: streets, mountain peaks, etc. Location descriptions can cover them all. Normally that is not too much of an issue because mailing address and these kind of location descriptions are very similar. You just run into trouble in countries like the US or UK where somebody thought it would be a good idea to use an entirely different system for mailing and they came up with the notion of postal towns. So your mailing address now includes the nearest town which happens to be responsible for delivering your mail. We don't  have very good data on postal towns in OSM which is the reason why Nominatim still doesn't include the concept. It needs to come up with a very clever form of guessing. There is an open issue for that: #1120 

Rechecking the boundary of Calabasas according to their city website, this really is the case you run into here. Good to know though that Tiger data has the postal cities. We probably could make use of that somehow.

**Comment by lonvia** [comment]
Closing here as postal cities are already tracked in #1120.
