### ISSUE TITLE
Cannot use object of type Nominatim\\Result as array

### ISSUE THREAD

**Issue by dg10a** [osm-search/Nominatim#1932]
I'm getting an unexpected result for this query:
https://nominatim.openstreetmap.org/search?city=SACRAMENTO&state=CA&format=json

Related issue in [geopy](https://github.com/geopy/geopy/issues/443).

**Comment by gatwtal** [comment]
Same error here for city name searches like

[https://nominatim.openstreetmap.org/search.php?format=json&json_callback=showResultsGeocode&q=Berlin](https://nominatim.openstreetmap.org/search.php?format=json&json_callback=showResultsGeocode&q=Berlin)

or

[https://nominatim.openstreetmap.org/search.php?format=json&json_callback=showResultsGeocode&q=Paris](https://nominatim.openstreetmap.org/search.php?format=json&json_callback=showResultsGeocode&q=Paris)

Other citys work without problems e.G.

[https://nominatim.openstreetmap.org/search.php?format=json&json_callback=showResultsGeocode&q=hamburg](https://nominatim.openstreetmap.org/search.php?format=json&json_callback=showResultsGeocode&q=hamburg)

This also happens when you try to search directly from openstreetmap.org with error messages like 
`"Error contacting nominatim.openstreetmap.org: undefined method attributes&#39; for nil:NilClass"`
