### ISSUE TITLE
after update --calculate-postcodes places still point to deleted postcodes

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#1937]
I removed a postcode 6800 from a place in Switzerland (it was surrounded by 69xx postcodes, clearly wrong and no secondary source). Based on Overpass  API query no other place in Switzerland has the 6800 postcode.

As expected `calculate-postcodes` (as described in http://nominatim.org/release-docs/develop/develop/Postcodes/) removed the entry from the `location_postcode` table.
```sql
SELECT * FROM location_postcode WHERE country_code='ch' AND postcode='6800';
(0 rows)
```

300 places still have the postcode in the `calculated_postcode` column
```sql
SELECTED osm_type, osm_id, class, type, rank_address, rank_search, name
FROM placex
WHERE country_code='ch' AND postcode='6800';
```

`select place_force_update` on those places didn't remove the postcode.

Example place https://nominatim.openstreetmap.org/lookup?osm_ids=N373429196&format=json
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=373429196

display_name | "Aquarello, Via Cattedrale, Quartiere Maghetti, Molino Nuovo, Lugano, Circolo di Lugano ovest, Distretto di Lugano, Ticino, 6800, Switzerland"
-- | --
class | "tourism"
type | "hotel"
importance | 0
address |  
tourism | "Aquarello"
road | "Via Cattedrale"
neighbourhood | "Quartiere Maghetti"
suburb | "Molino Nuovo"
town | "Lugano"
municipality | "Circolo di Lugano ovest"
county | "Distretto di Lugano"
state | "Ticino"
postcode | "6800" <====
country | "Switzerland"
country_code | "ch"

5 other postcodes which might have been already corrected in OSM possibly affected:
```sql
SELECT distinct postcode
FROM placex
WHERE country_code='ch' and postcode not in (
  SELECT postcode FROM location_postcode WHERE country_code='ch'
);
 postcode
----------
 29
 30
 6800
 9023
 BASEL
 CH-3656
```

Is this something the `calculate_postcodes` script can update? Or is the column also filled from other data (e.g. addr:postcode tags) and there's risk data gets overwritten?

**Comment by lonvia** [comment]
The `--calculate-postcode` update only recomputes the postcode table, it does not touch `placex`. That was intentional as already the postcode table computation is expensive enough. Updating placex would make this worse and I considered the overall gain minimal.

You can force a recomputation of the postcode by setting `indexed_state = 2` on the affected columns in placex. (`place_force_update` should work as well but is overkill in this case. Seeing `indexed_state` only affects the single object. `place_force_update` also affects all contained objects.) Not sure why it didn't work for you. Remember that you have to run `--index` after updating the rows. With that you can write your own clensing script to be run after `--calculate-postcodes`. We could also add that as an additional switch to `update,php`.

**Comment by mtmail** [comment]
I cleaned up more data and ran manual deletions. It looks like automating it will be too much of a performance impact for most users. For United States alone it would need a full table scan of the placex table and reindex 250.000 places every day.
