### ISSUE TITLE
Import-full.style modification issue

### ISSUE THREAD

**Issue by KamyarGhajar** [osm-search/Nominatim#1967]
Hi,

I am on version 3.5 of nominatim docker. I have modified the file import-full.style file to prioritize the place:* to boundary:* tag to generate a new row for it with class on type values. But it still is setting those values as boundary and administrative for places with tags such as place:neighbourhood or place:city. I am sure that the nominatim is using this file for importing data but why is this happening?

@lonvia would you please help me?

**Comment by lonvia** [comment]
You can't force separate rows for place tags in the style file. If Nominatim encounters the combination of `boundary=administrative` and `place=*`, it is hard-wired to generate a single column with class/type boundary/administrative and move the place tags into the extratags column. Nominatim needs these two values together as they are vital for the computation of the address hierarchy.

On the positive side, you don't need to prioritize the place value because it is always available for boundary administrative. Depending on what you want to do you can easily use that. For example, for the output templates the value is available as `extra_place`. If you wanted to preferably see the place type instead of boundary/administrative in json output, you could do something like this:

```
diff --git a/lib/template/search-json.php b/lib/template/search-json.php
index 4b896d0..67808ca 100644
--- a/lib/template/search-json.php
+++ b/lib/template/search-json.php
@@ -30,9 +30,9 @@ foreach ($aSearchResults as $iResNum => $aPointDetails) {
         $aPlace['place_rank'] = $aPointDetails['rank_search'];
         $aPlace['category'] = $aPointDetails['class'];
     } else {
-        $aPlace['class'] = $aPointDetails['class'];
+        $aPlace['class'] = isset($aPointDetails['extra_place']) ? 'place' : $aPointDetails['class'];
     }
-    $aPlace['type'] = $aPointDetails['type'];
+    $aPlace['type'] = isset($aPointDetails['extra_place']) ? $aPointDetails['extra_place'] :  $aPointDetails['type'];
 
     $aPlace['importance'] = $aPointDetails['importance'];
```

**Comment by KamyarGhajar** [comment]
Thank you for your conclusive response @lonvia .
