### ISSUE TITLE
consider short_name when searching for an address

### ISSUE THREAD

**Issue by freyfogle** [osm-search/Nominatim#1994]
In Germany there is a town with the official name "Oberndorf am Neckar"
https://www.openstreetmap.org/relation/943741

As you can see it has `alt_name: Oberndorf a. N.` and last week I added `short_name: Oberndorf`.

Adding short_name worked great, a search for "Oberndorf" now returns the town (along with many others who also have this common name). 

The problem is this:

A search for "Schulstr. 24, 78727 Oberndorf a. N., Germany"
https://nominatim.openstreetmap.org/ui/search.html?q=Schulstr.+24%2C+78727+Oberndorf+a.+N.%2C+Germany
correctly returns https://www.openstreetmap.org/way/566197096
which is tagged `addr:city=Oberndorf am Neckar`

But a search for "Schulstr. 24, 78727 Oberndorf, Germany"
doesn't return the correct house, instead wrongly returning another house in a different, distant postcode.

Perhaps short_name also can be considered in this case?

**Comment by lonvia** [comment]
`short_name` is already included. You can see that if you follow the [details link](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=566197096&class=building) for the Schulstr result and then from there go to the [details page for Oberndorf](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=943741&class=boundary).

The issue here is a slightly different one: Nominatim doesn't invalidate the search indexes for all containing objects when the name changes. It can be a very expensive operation and the gain is often minimal.

I've invalidated all of Oberndorf now.

**Comment by freyfogle** [comment]
thanks. 

A search for "Schulstr. 24, 78727 Oberndorf, Germany" on www.openstreetmap.org now works perfectly.

But a search on nominatim.openstreetmap.org still doesn't
https://nominatim.openstreetmap.org/ui/search.html?q=Schulstr.+24%2C+78727+Oberndorf%2C+Germany

what is the difference?

**Comment by lonvia** [comment]
I assume you are in Spain. Then you are routed to a different server. I've only invalidated the one.

**Comment by freyfogle** [comment]
ok, fair enough. thanks
