### ISSUE TITLE
Address hierarchy on buildings without housenumber

### ISSUE THREAD

**Issue by geoneutrino** [osm-search/Nominatim#2064]
Hi
I'm a bit confused on /details endpoint for some objects. E.g. this building with addr:* tags but no housenumber shows no "address hierachy" but only place:country=hungary
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=855889331
and although its a building the /details shows type=place:postcode

The building on the other side of the street with the same addr: tags but additionally a housenumber shows a correct output with region, county, village and so on
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=855889334&class=building

Shouldn't the details be correct in the first case too as we have all needed informations from the addr tags ?

Edit: seems to be initial import related as the object is as place=postcode is in the database

**Comment by lonvia** [comment]
Nominatim looks for an interesting main tag for classifying object. `building=*` alone is not one of them. That's an optimisation to prevent the millions of HOT-generated `building=yes` around the world to be imported. They would blow up the database size with absolutely no gain for searching. `addr:*` tags are mostly there to provide secondary information. `addr:*number` and/or `addr:housename`  are needed to make it a first class address object (again, anything else would add a lot of data to the database that is not searchable in any meaningful way).

That leaves `addr:postcode`. That is a bit of an outlier. It is only secondary information as well but we use postcodes to create artificial postcode areas. That's why they end up in the database. But they are not searchable as points either, so they do not receive the full treatment of getting an address. That's why you only see the country. Long term, the plan is to remove them completely from the public view, see #2049. In the meantime, you still get them for technical reasons.
