### ISSUE TITLE
Naming/translation of places and administrative boundaries

### ISSUE THREAD

**Issue by sanderd17** [osm-search/Nominatim#2078]
When searching for a municipality in Belgium, you very often get two or even three or four results based on the different `admin_level`s.

You get a "Stad" or "Dorp" ("City" or "Village"), or a "Administratieve grens" ("Administrative boundaries"). In Dutch, the first ones sound as a point feature: the city centre. The Administrative boundary gives no details on what it is. But in Nominatim those represent the `admin_level=8` boundary which are municipalities in Belgium. "Gemeente" or "Gemeentegrens" would be a better translation. The municipality is what people will most likely search for in case the names are equal.

There's also a "Stadsgrens" (probably translated from "City limit"), which has no strict meaning in Dutch. If you click on it, you get the `admin_level=9` boundary, which represents the part-municipality (a subdivision of municipalities). Many municipalities use the same name as their biggest part-municipality. Hence why there are two confusing results. "Deelgemeente" would be a better translation.

When you search for a city, you're also likely to find an "arrondissement" (`admin_level=7`) with the same name. Arrondissements are historic subdivisions, and are almost obsolete. They are just used for some administration citizens almost never get in touch with. These are named "Districtgrens" but should definitely be named "Arrondissement". Districts are used in Belgium for part-municipalities that also have their own governing body. At the moment only the city of Antwerp has those. So "District" should never be used unless you want to make an exception for Antwerp.

We also have some provinces (`admin_level=6`) that are named after their province capital. Those appear as "Staatsgrens". Belgium doesn't use "State" as an administrative division, so this makes no sense either. Those should be named "Provincie".

So my question is, does Nominatim offer the possiblity to alter those terms per region? If so, where can I suggest these?

![2020-11-27-093014_347x363_scrot](https://user-images.githubusercontent.com/562171/100428027-aa466d00-3093-11eb-848f-22b7801e2749.png)
![2020-11-27-093317_351x410_scrot](https://user-images.githubusercontent.com/562171/100428030-ac103080-3093-11eb-88f6-a1404ef15d2b.png)
![2020-11-27-094821_340x376_scrot](https://user-images.githubusercontent.com/562171/100429502-b4696b00-3095-11eb-9b88-63f048c5a56e.png)

**Comment by lonvia** [comment]
It looks like you are talking about the display of search results on the OpenStreetMap website. That's the websites logic, so it should be discussed there.

That said, the OSM website uses two pieces of information to determine the prefix for boundaries. If possible, it takes the designation of either a place tag or a linked place node. That is the preferred way because place allows to nicely distinguish between things like province and state or city and town. If no place information is available, the website makes up a "blah boundary" name from the address rank reported by Nominatim. The address rank is basically the admin_level adapted by country [with some adaptions](https://nominatim.org/2020/11/11/places-and-boundaries.html). I've recently adapted the mapping for Belgium (see #2041) and they are now: 4 - region, 6 - state, 7 - county, 8 - municipality, 9 - city, 10 - suburb This will come into full effect next week after a reimport of the database.

There won't be more of a per-region adaption than that because it simply wouldn't scale against the translations.

Side note: Looking at the examples you provide, there seems to be a bit of a mess with the wikidata tags. Kortemark at [admin level 8](https://www.openstreetmap.org/relation/1376932) and [admin level 9](https://www.openstreetmap.org/relation/1324318) point to the same wikidata item even though they look to be distinctly different boundaries. This is confusing Nominatim because there is also a [place=village](https://www.openstreetmap.org/node/710861570) with the same wikidata tag. Eventually it links them all up. Looking at the history, those wikidata tags are still from Yurik's automatic mass import. It would be great if the Belgian community could review those.

**Comment by sanderd17** [comment]
Hi Sarah, Thanks for the answer.

I didn't know Wikidata tags had an influence on Nominatim. I never understood the use of wikidata for stuff that can be encoded with regular tags, so I never looked into those tags. I'll now take a look at cleaning them up.

But the terminology still quite confusing. Before 1970, a municipality was either a city or a village. Cities were those municipalities that have been granted city rights by the Belgian state. Usually because they had city walls and a belfry. But in the 70's, it was agreed that many municipalities were too small to govern efficiently. So many municipalities merged together. One city got neighboring villages under its city council. But similar-sized villages also merged together to form a new municipality. The former municipalities became known as submunicipalities. The city title (if present) was transferred to the new municipality. The term "village" however has completely lost any official meaning but is still often used to refer to a village center.

The pre-1970 boundaries are still marked with road signs, and often for addressing. Hence they are still in OpenStreetMap. Those are encoded as admin level 9 boundaries.

Due to the inheritance of the city title since medieval times, it often has no real meaning in today's life. There are very small cities around, like Mesen, that only have about 1000 inhabitants. And we chose not to use the city title to mark a place as city in OpenStreetMap. Instead we tried to use local importance, expressed in number of inhabitants. Less than 10000 inhabitants is a `place=village`, between 10 000 and 100 000 inhabitants is a `place=town`, and more than 100 000 is a `place=city`. Admittedly, those were historically chosen to please the renderer and match the English situation. Otherwise we would have no towns, and could not make a distinction between big and small cities. 

So an admin level 8 boundary is always a municipality, but can be called a city when it has the title. It is never called a village.
An admin level 9 boundary is always a former municipality, now named partmunicipality or submunicipality. 
Admin level 10 isn't used, perhaps only in some very special situations.

A point feature can be called a village center or a city center (or anything smaller like a hamelet). 

I know this is all very complicated, and is impossible to scale to other regions. But would there perhaps be an option to add a `title` tag to the boundaries and place nodes? That way mappers could force how the results would show up on the site. Or is that something that should be implemented on the site level?

**Comment by lonvia** [comment]
No, there is no way that we add a tag for the title you want to see in the search results because we'd end up with a completely untranslatable mix of terms that have only limited meaning for people not familiar with the area. There is a good reason we have agreed on a fixed set of `place=*` terms in OSM. It gives us something that is usable on a planet scale.

You seem to have developed a good, consistent definition of when to use which place type. That's really all you need. Map the places with place nodes. Add the administrative boundaries. Make sure to link  the two where the area of the place described by the node is the same as the one covered by the boundary. If you do that consistently then Nominatim will be able to sort out all the cases you have just mentioned.
