### ISSUE TITLE
Space implosion - Europe import

### ISSUE THREAD

**Issue by Azbesciak** [osm-search/Nominatim#2116]
**Describe the bug**
Hello, I initially reported the issue to the docker image repository, because I am using mediagis/nominatim:3.5
Issue: https://github.com/mediagis/nominatim-docker/issues/164
Later I checked additionally placed their scripts and everything looks normal.
So the question is - why it takes so much space? On the doc page, it is said that 900 GB is at least required for the whole planet. It already took 511 GB just for Europe (latest from geofabrik). Import failed after step 30 on index preparation because of no more space.

**Software Environment (please complete the following information):**
- Nominatim version: 3.5
- Postgresql version: 12
- Postgis version: 3
- OS: Ubuntu 18.04

**Hardware Configuration (please complete the following information):**
- RAM: 16 GB
- number of CPUs: 4
- type and size of disks: 512 SSD
- bare metal/AWS/other cloud service: Azure VM

**Postgresql Configuration:**
docker image https://github.com/mediagis/nominatim-docker/tree/master/3.5

**Additional context**

**Comment by lonvia** [comment]
I'm sorry but there is not much we can do. OSM data simply has become huge. Just a back-of-the-envelope computation:

Europe makes up about 50% of the planet. Of the 900GB about 70 go to the flatnode file which always has the same size independent of what you import. So that means at least 500GB are necessary just for the import. A 512GB SSD probably has about 480GB usable space of which 20GB are used by the OS. Another 22GB are used by the Europe data file. That leaves 440GB which is not sufficient for the import of Europe.

**Comment by Azbesciak** [comment]
Unfortunately, the whole drive is attached only for the Postgres database, also I removed the OSM file so the whole DB file takes so much. The question is where is the limit?

**Comment by lonvia** [comment]
You won't get a hard answer to that. OSM data is simply growing to quickly to give a number that wouldn't be outdated tomorrow. In addition, the actual use depends on how you configure your OS, your Postgresql and your Nominatim setup. Not to mention that 3.5 has different requirements than 3.6.

The ballpark estimates from the documentation is all we can do. Sorry.
