### ISSUE TITLE
reverse php file issue

### ISSUE THREAD

**Issue by raviteja-karri** [osm-search/Nominatim#2120]
After cloning and build the new reverse php file has issues while initiating the process.
The file has a relative path to settings-frontend.php file where the file does not exists.
I have to manually rewrite settings.php and restart the service to fix this issue.

**Comment by mtmail** [comment]
Please add full details to the issue report: Nominatim version, file paths, what had to be rewritten to what and how has that been done. What does cloning mean in this context, what does "build the new reverse php file" mean in this context? What is "new reverse php file" since you don't mention what has there been before.

**Comment by raviteja-karri** [comment]
After cloning the latest version and compiling as mentioned
The compilation process created a build folder with the website folder where reverse geocoding has path issue where it cant find the file.

**Comment by mtmail** [comment]
Please tell us specific paths, error messages, which files you edited to fix the issue on your machine. We can’t even start to look into the issue without more information.
