### ISSUE TITLE
Use current OSM location to increase importance

### ISSUE THREAD

**Issue by boothym** [osm-search/Nominatim#2211]
Not sure if this is something for the OSM website or Nomination. Didn't know what to search for so hopefully it's not a duplicate issue! 

Recently on OSM.org I searched for **Glencoe** - which is a village in Scotland - however Nominatim returned Glencoe, Illinois. https://nominatim.openstreetmap.org/ui/search.html?q=glencoe

I noticed that if Glencoe, Scotland was in my bbox on OSM - for example https://www.openstreetmap.org/#map=10/56.6608/-5.0111 - then Nominatim would return Glencoe, Scotland.

But if I zoomed the OSM map into Edinburgh - https://www.openstreetmap.org/#map=11/55.9807/-3.1963 - then Nominatim would once again return Glencoe, Illinois.

Could Nominatim be adjusted so that places in the country that a user is looking at are prioritised in the search results? It's likely people will want to find places in their own country/area first.

A similar thing occurs when searching for Perth - if my OSM bbox is in the UK or Scotland then I am unlikely to want Perth, Australia as the top search result.

**Comment by otbutz** [comment]
https://nominatim.openstreetmap.org/ui/search.html?q=glencoe&viewbox=-19.88525%2C61.66004%2C21.86279%2C48.86672

Advanced options > [x] apply viewbox

**Comment by boothym** [comment]
Thanks, but as I mentioned in the third paragraph when the viewbox/bbox includes Glencoe, Scotland then it is already found correctly by Nominatim. 😉 I'm looking for it to be found when the viewbox is further away but still in the same country.

**Comment by lonvia** [comment]
"Same country" is not a very consistent measurement. When zoomed in on Detroit, you are much likely to search for 'Lakeshore' in Canada, which is a couple of kilometers away, than for Lakeshore, California at the other end of the continent but in the same country.

The way that the viewbox is applied is currently not ideal because it provides a hard cut-off and the size of the viewbox is not taken into account. This needs to be improved but simple distance is likely a more reliable measure.

Improving the viewbox handling is already covered by #824, so closing here.
