### ISSUE TITLE
Admin levels and place types in China

### ISSUE THREAD

**Issue by AlexanderMisel** [osm-search/Nominatim#2251]
## What did you search for?

- 泥沟村 (Node 7327126075)

## What result did you get?

- 泥沟村, 石家庄市, 河北省, 中国

## What result did you expect?

- 泥沟村, 韩村镇, 赵县, 石家庄市, 河北省, 中国

## Further details

As in China, cities are larger than counties, we are suggested to tag (per https://wiki.openstreetmap.org/wiki/Chinese_tagging_guidelines)
- city (市): admin_level=5, place=city
- county (县): admin_level=6, place=city
- town (镇): admin_level=8, place=town

This made nominatim to have 
- 赵县 (Relation 3290467, county, address rank 18) 
- 韩村镇 (Relation 12529959, town, address rank 20)

whose address rank being not more than a village like 泥沟村 (Node 7327126075, village, address rank 18). I think this is the reason why I didn't get my desired result.

**Comment by lonvia** [comment]
The problem here is that you are using the same tagging for rural and urban areas. That usually doesn't work. You need to use proper `place` types depending on where you are to make addressing work properly. Here is what I would do in terms of tagging:

* admin_level=5: always use place=region(?) unless the prefecture-like city only consists of the city proper and has no rural parts
* admin_level=6: use place=county for rural counties, place=town/city for city-like counties and place=district for inner-city districts
* admin_level=8: use place=town for towns and place=suburb for sub-districts
* add a multipolygon with place=city around the districts of a prefecture like city to mark the city proper

What I'm trying to say here is that there is no need to define a 1:1 relation between place types and admin_levels. They serve a different purpose. admin_level describes the governmental hierarchy while the place tag describes the type of an area as described by everyday use. In terms of the table in the 'Chinese tagging guidelines', you should define the proper place type for each of the types listed in the comments not for the admin level.

Once you refine the place types in that way, Nominatim will be able to shift around the areas ad necessary to make sure that the expected parts appear in the address.

**Comment by AlexanderMisel** [comment]
Thanks for you reply. I discussed with Chinese OSM friends on this tagging problem, and came to know why they use `place=city` for both cities and counties. There's a fact that OSM only renders name and center point of cities as desired, counties or municipalities doesn't have their names rendered on map like `place=city` do. In China, it's a convention to show counties as point on map. So the tagging maybe cannot change unless the rendering of OSM support that. And it seems `place=region` is not recommended to use.

By the way, I think promoting the rank of city in configuration might also solve this problem, for example
```json
{ "countries" : [ "cn" ],
  "tags" : {
      "place" : {
          "city" : 14
      }
  }
}
```

**Comment by lonvia** [comment]
https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer

There is nothing I can do for the Chinese community in that case. Sorry.

**Comment by c933103** [comment]
> Thanks for you reply. I discussed with Chinese OSM friends on this tagging problem, and came to know why they use `place=city` for both cities and counties. There's a fact that OSM only renders name and center point of cities as desired, counties or municipalities doesn't have their names rendered on map like `place=city` do. In China, it's a convention to show counties as point on map. So the tagging maybe cannot change unless the rendering of OSM support that. And it seems `place=region` is not recommended to use.
> 
> By the way, I think promoting the rank of city in configuration might also solve this problem, for example
> ```json
> { "countries" : [ "cn" ],
>   "tags" : {
>       "place" : {
>           "city" : 14
>       }
>   }
> }
> ```

OSM have a lot of thing that aren't in line with Chinese mapping convention. I think it's advisable to create a Chinese version stylesheet like the French style and German style of OSM in order to achieve the desired rendering result, instead of trying to adopt the place=* tag accorng to redeer, which eaxh OSM data user will have their own dofferent ways of handlimg the situation

**Comment by 1ec5** [comment]
Chinese place tagging practices are also being discussed in [this thread on the tagging mailing list](https://lists.openstreetmap.org/pipermail/tagging/2021-May/thread.html#61445).

> In China, it's a convention to show counties as point on map. So the tagging maybe cannot change unless the rendering of OSM support that. And it seems `place=region` is not recommended to use.

Does this refer to putting a label for the county near the centerpoint of the county? That can be achieved using administrative boundary relations without the need for a `place=city` POIs. In fact, gravitystorm/openstreetmap-carto#4100 has added county labels at z10+ that are consistent with the labeling of provinces and prefectures at lower zoom levels, based on boundary relations, but the `place=city` POIs are now colliding out those labels. It sounds like deleting these county POIs or retagging them as `place=region` would be a win-win situation, no?

**Comment by lonvia** [comment]
This is the issue tracker for the Nominatim software. This really is not the right place to discuss Chinese place tagging.
