### ISSUE TITLE
Cannot find by name that includes a number

### ISSUE THREAD

**Issue by richlv** [osm-search/Nominatim#2364]
## What did you search for?

Searching for "2. slimnīca" (with and without doublequotes).
https://nominatim.openstreetmap.org/ui/search.html?q=2.+slimn%C4%ABca
https://nominatim.openstreetmap.org/ui/search.html?q=%222.+slimn%C4%ABca%22

## What result did you get?

All kinds of "slimnīca".
<img width="386" alt="image" src="https://user-images.githubusercontent.com/112888/121863935-06f23800-cd05-11eb-89f3-6566213faf62.png">

## What result did you expect?

https://www.openstreetmap.org/way/87364407
https://www.openstreetmap.org/relation/1407629

**Comment by lonvia** [comment]
It's intended that you get results for 'Slimnica' in this case but only streets or villages. Returning bus stops is a bug. A side effect of #1874.

**Comment by richlv** [comment]
Finding bus stops is actually beneficial in some cases, but is there any way to find the actual hospital with that search string?

**Comment by mtmail** [comment]
The hospital's (https://www.openstreetmap.org/relation/1407629) name is "Rīgas 2. slimnīca" so you'd need to search for https://nominatim.openstreetmap.org/ui/search.html?q=R%C4%ABgas+2.+slimn%C4%ABca Nominatim doesn't support searching for partial names (see https://github.com/osm-search/Nominatim/issues/94)

If "2. slimnīca" is the name local people use, one could add additional name tags https://wiki.openstreetmap.org/wiki/Key:name to the OSM relation.

**Comment by lonvia** [comment]
Long story of what happens: Nominatim first searches for something called "2. slimnīca" and doesn't find anything. Next it tries the interpretation of "a street called slimnīca with housenumber 2". And that is the part that goes wrong. If it would be doing this right, it would not return bus stops at this point because bus stops don't have house numbers attached. If that gets fixed, then Nominatim will very likely not find anything useful with the interpretation of a street and go on to look for partial name matches. It's likely that you still don't get useful results afterwards because a "2" in a partial search doesn't work well but that then falls under the general known issue of "Nominatim sucks at partial matches".

**Comment by richlv** [comment]
Got it, thank you for the detailed info. Looks like "loc_name" might be a good fit here.
