### ISSUE TITLE
`hierarchy` from details.php is incomplete

### ISSUE THREAD

**Issue by foodev** [osm-search/Nominatim#2439]
When I lookup the [place details](http://nominatim.org/release-docs/develop/api/Details/) with `hierarchy=1&group_hierarchy=1` I get an incomplete hierarchy for the administrative areas.

Examples:

**Germany** has [16 states](https://en.wikipedia.org/wiki/States_of_Germany#List) but I get none:

https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=51477&linkedplaces=0&hierarchy=1&group_hierarchy=1&format=json

**Berlin, Germany** has [12 boroughs](https://en.wikipedia.org/wiki/Boroughs_and_neighborhoods_of_Berlin#Boroughs) but I only get nine:

https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=62422&linkedplaces=0&hierarchy=1&group_hierarchy=1&format=json

**Regierungsbezirk Düsseldorf, Germany** has [15 counties/independent towns](https://en.wikipedia.org/wiki/D%C3%BCsseldorf_(region)) but I get none:

https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=63306&linkedplaces=0&hierarchy=1&group_hierarchy=1&format=json

All the places do exist in OpenStreetMap and the Nominatim database.

If I understand correctly [you use the `parent_place_id` to find the children](https://github.com/osm-search/Nominatim/blob/18554dfed767d8ef669e15014a5b0382ad8bab43/lib-php/website/details.php#L204-L228). Probably there's a problem with the calculation of the `parent_place_id`? With a PostgreSQL query like this I do find the places (in this example the Berlin boroughs). Maybe it would be better than using `parent_place_id` for the hierarchy?

```sql
SELECT
    p2.place_id,
    p2.osm_type,
    p2.osm_id,
    p2.name -> 'name' AS name
FROM placex AS p1
LEFT JOIN placex AS p2
    ON (
        p2.osm_type = p1.osm_type
        AND p2.class = 'boundary'
        AND p2.type = 'administrative'
        AND p2.admin_level = 9
        AND ST_COVERS(box2d(p1.geometry), box2d(p2.geometry))
        AND ST_AREA(ST_DIFFERENCE(p2.geometry, p1.geometry))/ST_AREA(p2.geometry) < 0.001
        AND p2.country_code = p1.country_code
    )
WHERE p1.osm_id = 62422
AND p1.osm_type = 'R'
```

**Comment by lonvia** [comment]
The details output is a debugging tool that exposes the internal database structure. In the case of `hierarchy` it exposes the hierarchy created by `parent_place_id`. This has not necessarily anything to do with administrative hierarchies. And as it happens, it is not really relevant because `parent_place_id` has close to no use for places with rank_search < 30.

If you were planning to extract hierarchies from the public API via the details API, then please don't. It would be a violation of our usage policy.

With your own database, you have to indeed query the database directly. You can do it faster using the `place_addressline` table which creates a relation between a place and all the places that form its address, i.e. all the boundaries it is in. So the query above would be simpler:

```
SELECT p2.* FROM place p1, placex p2, place_addressline pa
WHERE p1.osm_id = 62422 AND p1.osm_type = 'R'
      AND pa.address_place_id = p1.place_id
      AND pa.place_id = p2.place_id
      AND pa.isaddress AND pa.fromarea
      AND p2.admin_level = 9
```

**Comment by foodev** [comment]
I didn't plan to extract hierarchies from the public API - I would've used an own installation. But thanks for your query. That looks much faster than using `geometry` :+1: 

I wonder why there's API endpoint for hierarchies though...

**Comment by lonvia** [comment]
> I wonder why there's no API endpoint for hierarchies though...

It's a rather expensive operation, so I don't think we will ever do an API endpoint. Extracting the information offline is another story.

The nominatim tool does have an`export` option which allows you to dump all places inside a region. That kind of does what you want. The problem is that it is an old, crappy script which needs first of all porting to python and second some general reworking to make it really useful.

**Comment by foodev** [comment]
Your query works great to get the children of a given relation. Unfortunately for Germany "Regierungsbezirk" is not having any children (according to `place_addressline`).

I understand that this was a deliberate change (https://github.com/osm-search/Nominatim/issues/1634#issuecomment-573292776) and it is configurable. But how can I configure it? I don't find any documentation for it.

My main goal is to get all `type=boundary, boundary=administrative` and the hierarchical structure (relation A has the children B and C and B has the children D and so on...).

**Comment by mtmail** [comment]
Maybe https://osm-boundaries.com/ is a better tool to extract the boundaries. On the left-hand side you can right-click so select children of countries. Below the map you can select what fields to extract. It's not obvious from the user-interface I think. https://help.openstreetmap.org/ might have more hints how to accomplish your project with other tools.

**Comment by lonvia** [comment]
This is really starting to be a conversation for the discussion section...

If you want to use Nominatim to just get a boundaries database, you should start with the [admin style](https://nominatim.org/release-docs/latest/admin/Import/#filtering-imported-data). You can trim it further down and remove the place and landuse sections. The file format is described [here](https://nominatim.org/release-docs/latest/develop/Import/#configuring-the-import).

Skipping certain admin levels is done in [address-levels.json](https://github.com/osm-search/Nominatim/blob/master/settings/address-levels.json). Remove all the country specific sections and you are good. Basic documentation for that file is [here](https://nominatim.org/release-docs/latest/develop/Ranking/#rank-configuration).
