### ISSUE TITLE
Names of linked places should be searchable

### ISSUE THREAD

**Issue by Janjko** [osm-search/Nominatim#2500]
## What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?city=Vela+Luka
https://nominatim.openstreetmap.org/ui/search.html?city=Vela+Luka&country=Croatia

## What result did you get?

No results

## What result did you expect?

https://www.openstreetmap.org/node/95241963

## Further details

If I put the county as a search term, the boundary of the city is found, but the node is still not found:

https://nominatim.openstreetmap.org/ui/search.html?city=Vela+Luka&county=Dubrovnik-Neretva+County

**Comment by lonvia** [comment]
The Vela Luka node gets merged with the relation "Općina Vela Luka" because both have the same wikidata tag, indicating they are the same place. So far so good. The problem then is that the names from the relation take precedence and those names all include the category indicator (opcina/commune) which then makes your search a search for a partial term. And that goes wrong here because 'vela' and 'luka' are very frequent terms.

We really need to keep both sets of names when merging place nodes and boundary relations.

**Comment by Janjko** [comment]
Well, I'm not sure the town should have the same wikidata tag as the municipality. The wikipedia article talks only about the town Vela Luka, not about the few extra hamlets in the municipality. I think I'll remove the wikidata tag from the relation.

I'm guessing the merging will create a lot of searching mistakes because I have a felling lots of mappers will add the same wikidata tag to both. Maybe I'm wrong.

Anyway, I removed the wikidata tag and now it works. Thank you very much!

**Comment by lonvia** [comment]
The linking was likely fine from a point of a search engine. The wikipedia article at least is certainly about the municipality and town.

In any case, the issue of making sure tht names of linked places are searchable remains. Reopening.
