### ISSUE TITLE
TIGER housenumbers need to trigger preference of attached street in search

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2501]
For a house-number search on very long roads (many OSM ways sharing the same address, e.g. same name in the same city) Nominatim has a hard limit how many OSM ways it inspects for the house number. The limit is currently 40 (https://github.com/osm-search/Nominatim/commit/c5109d39d029fb013286e4ff4220e200267caa09)

Example:
5958 W Parker Rd Plano, TX
https://nominatim.openstreetmap.org/ui/search.html?q=5958+W+Parker+Rd+Plano%2C+TX

Here the street is found, the house number isn't.

TIGER raw data contains an entry with the house number range
`5999;5967;all;W Parker Rd;Collin;TX;75093;LINESTRING(-96.829104 33.045395,-96.828222 33.045442)`

https://nominatim.openstreetmap.org/search.php?q=5958+W+Parker+Rd+Plano%2C+TX&format=jsonv2&debug=1
shows
```sql
SELECT place_id, address_rank, ( SELECT count(*) FROM ( SELECT unnest(
[...]
DESC, - abs(26 - address_rank) + 3 DESC, exactmatch DESC LIMIT 40
```

The returned list of place_ids is pretty much random here because all OSM ways have the same rank and there's no further ordering clause (e.g. by place_id, by distance). In this case we have 168 OSM ways. On different servers I found a different set house numbers of that street not found. Increasing the limit leads to the housenumber being found.

I know increasing the limit makes forward search slower, there's no one ideal settings. It would be great if admins can configure the limit.

**Comment by lonvia** [comment]
The limit isn't your issue here.

When we look up the address in the search_name table they are already ordered such that streets that have the requested house number attached are floating on top. The problem is that we only [check against the placex and location_property_osmline table](https://github.com/osm-search/Nominatim/blob/master/lib-php/SearchDescription.php#L586), not against the location_property_tiger table. So the fix is to look into the TIGER table too. This will be fun because that query is already causing a lot of headache and making Nominatim pretty much unusable on PostgreSQL before version 11.
