### ISSUE TITLE
Some words have too many tokens in the word database

### ISSUE THREAD

**Issue by 7171bel** [osm-search/Nominatim#2506]
## What did you search for?
2, 5-й Микрорайон, Речица, Речицкий район, Гомельская область, Беларусь

## What result did you get?
no results
## What result did you expect?
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=175292264&class=building
**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

**Comment by 7171bel** [comment]
1. Why this request was work on previous version of nominatim server? 
2. Why the same scheme is working with streets: 48, Советская улица, Речица, Речицкий район, Гомельская область, Беларусь?
3. Why result of request "5-й микрорайон 2, Речица, Речицкий район, Гомельская область, Беларусь" is look like "2, 5-й микрорайон, Речица, Речицкий район, Гомельская область, 247491, Беларусь", but there are no results on the same request "2, 5-й микрорайон, Речица, Речицкий район, Гомельская область, 247491, Беларусь"? 
![Uploading Screenshot_20211103-180711.png…]()

**Comment by lonvia** [comment]
There is a regression somewhere in the code. The information from the original bug report is sufficient to track it down.

**Comment by lonvia** [comment]
I've pushed a temporary fix. A full fix really needs some more fundamental changes which will take a while. Leaving this issue open for now.

**Comment by lonvia** [comment]
To add some context: the problem here is that some normalized versions of words have a lot of tokens in our word table now. In this case the problematic ones are '2', '5' and 'belarus'. This leads to an explosion of search candidates so that Nominatim will give up the search well before it gets to the correct candidate. The fundamental change needed here is that tokens with the same normalization are merged, so that there is only one search candidate for all forms.

Title of issue adapted to better relocate it later.

**Comment by lonvia** [comment]
Tokens with the same transliteration are now combined and only result in a single search being emitted.
