### ISSUE TITLE
Can't pull shapefile for San Jose

### ISSUE THREAD

**Issue by DuongVu39** [osm-search/Nominatim#2521]
## What did you search for?

I was trying to pull shapefile for the city of San Jose and no matter what I did, it seems like I couldn't find it in the database. This only happened with the city of San Jose, California, US so far.

## What result did you get?
I used osmnx to query from Nominatim. Here's the error message I got:
```
ValueError: Nominatim geocoder returned 0 results for query "San Jose, California, USA"
```

**When the result missing completely:**
Then I tried to look at OpenStreetMap website to find San Jose ID, this is the result I got: https://www.openstreetmap.org/relation/112143#map=11/37.3108/-121.8967
This gives me ID: 112143 and I tried both 112143 and R 112143 id with osmnx python and both told me that Nominatim returned 0 results.

**Comment by mtmail** [comment]
https://nominatim.openstreetmap.org/ui/search.html?q=San+Jose%2C+California%2C+USA finds the node https://www.openstreetmap.org/node/1690212988 of the city. The relation https://www.openstreetmap.org/relation/112143 is not imported by Nominatim because it contains errors (unconnected or mis-sorted ways).

**Comment by mtmail** [comment]
I fixed the relation, so it should work now. (It's non-obvious because on the map it looks alright, there were duplicated ways on top of each other)

**Comment by DuongVu39** [comment]
Thank you! It works now!
