### ISSUE TITLE
Query /search endpoint with OSM Object type

### ISSUE THREAD

**Issue by cpwnd** [osm-search/Nominatim#2536]
**Is your feature request related to a problem? Please describe.**

I'm querying the Nominatim API with a City name. In ca. ~95% of the time I'm getting the city administrative relation objects. In the other case I get the city node object. For example when I search for Berlin, the response contains the node object of the city of Berlin. 

**Describe the solution you'd like**

At the moment my solution is to resolve the relation object from the wikidata entity (which lives in the extra tags of the response of the /search response) of the node out of the reponse e.g. in the case of Berlin.
In my opinion a solution would be the possibility of defining a parameter osm object type on the search endpoint.

**Describe alternatives you've considered**

Alternatively I can also search through the collection of results in a response to get a object with relation type, right now.
I can also understand if knowledge about osm (node-, relation-, way-types) is not part of the knodwledge wich a user of the api has and therefore are not considered as api parameters for the search endpoint.

**Additional context**

**Comment by cpwnd** [comment]
Ok I just read the warning box in docs
> Warning
> Special phrases are not suitable to query all objects of a certain type in an area. Nominatim will always just return a collection of the best matches. To download OSM data by object type, use the Overpass API.

**Comment by lonvia** [comment]
Nominatim probably should return relations before node types when all other things are equal. That would be consistent with what it otherwise does when it manages to figure out that nodes and relation refer to the same object.

The particular problem with Berlin here is really with the OSM data. Berlin has a place=city and place=state node and that throws off Nominatim because it really doesn't expect multiple place nodes for the same object. Maybe we should add that as a feature.

As for searching for a particular object type, I don't like that idea too much because it is an indirect solution for your actual problem: you would like to have a result with an area geometry returned. If the area came from a particular OSM object type is not really relevant. At least I presume that this is the case.

**Comment by cpwnd** [comment]
> Maybe we should add that as a feature.
Sounds good. So after adding the multiple-place-nodes feature, Nominatim would than figure out that the Berlin node (with one place) and Berlin relation (with two places) refer to the same object? For example because both objects have an attribute place=city, regardless of the other matching attributes like name etc. ?

> At least I presume that this is the case.
Yes thats right.

**Comment by cpwnd** [comment]
I searched for more cities where Nominatim has similar behaviour and found one. But the city hasn't the same kind of attributes like Berlin. In case of Algier, with https://nominatim.openstreetmap.org/ui/search.html?q=Algier I get the two topmost responses first the node place=city and second one the relation boundary:administrative (but here the node Algier hasn't multiple place attributes. Would Algier benefit also from your proposed feature from above?).
With https://nominatim.openstreetmap.org/ui/search.html?city=Algier I only get node(place=city) and I think that you already explained above.

Tirana the search response is like you described above, so everything ist fine.
Here I have another question, sorry to mix it in this issue.
Simple https://nominatim.openstreetmap.org/ui/search.html?q=Tirana and structured https://nominatim.openstreetmap.org/ui/search.html?city=Tirana. For this I have a question, Sorry for posting it here. 
For Tirana in its wikidata entry the claim for Openstreetmap relation id is missing, but Nominatims response displays it correctly? How is that, is this part of the wikipedia/wikidata import?

Maybe the case of Algier helps to refine the feature and nevertheless thank you for your work.

**Comment by lonvia** [comment]
I've fixed Berlin (and Hamburg) now on the data side by deleting the state-Nodes. Leaving the ticket open until I've switched the type order.

As a general rule, if you don't get the area back, then it either doesn't exist or there is a data issue in OSM that prevents Nominatim from making the link between relation and node. For Algier there is no area releation. What you get as second result is the province.

Wikidata links Nominatim uses go from OSM to wikidata. 

Please use the Discussion section for questions instead of goiing off-topic in issues.

**Comment by lonvia** [comment]
Investigating this a bit further, it does not really make sense to reorder by type be cause the results are never really the same. In the example with Berlin one of the results was classified as state, the other as city. The ordering right now is such that the city usually is preferred and that is usually the right thing to do when the places are distinct.

So I'm afraid this is a won't fix from the Nominatim server side. You have to filter results on the client side if you want to drop results without an area.
