### ISSUE TITLE
Issue with Documentation build

### ISSUE THREAD

**Issue by champagne-cmd** [osm-search/Nominatim#2661]
I attempted to build the docs as described in the development setup instructions by going to the build folder and running 'make docs'. However, I get the following error: 

`ERROR    -  Config value: 'pages'. Error: The configuration option 'pages' was removed from MkDocs. Use 'nav' instead.
Aborted with 1 Configuration Errors!
make[3]: *** [docs/CMakeFiles/doc.dir/build.make:60: docs/CMakeFiles/doc] Error 1
make[2]: *** [CMakeFiles/Makefile2:1119: docs/CMakeFiles/doc.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1126: docs/CMakeFiles/doc.dir/rule] Error 2
make: *** [Makefile:604: doc] Error 2`

It appears the latest release of MkDocs removes the `pages` config option and replaces it with `nav`. I fixed this locally by modifying the `mkdocs.yml` file in the build directory. I'm not sure whether this is due to something outdated in Nominatim or with something else in my build software.

**Software Environment (please complete the following information):**
- Nominatim version: 4.0.1
- Postgresql version: 12.9
- Postgis version: 3.0.0+dfsg-6ubuntu4
- OS: Ubuntu 20.04

**Comment by lonvia** [comment]
There has been a deprecation warning for a while. We've left it for now to be able to keep supporting older versions of mkdocs, in particular the version shipped with current Ubuntu LTS. However, if I remember correctly, there are other issues with that version by now. So that argument is mute.

In short: yes, this should be changed. Do you feel like making a PR? The mkdocs.yml template is in `docs`.

**Comment by champagne-cmd** [comment]
Yes, this seems like a basic change, I can look into making a quick PR.
