### ISSUE TITLE
Reverse returns point far away rather than closer road

### ISSUE THREAD

**Issue by eliboni** [osm-search/Nominatim#2720]
Reverse lookup seems to work just great in Europe, but often in US or Africa I got a strange behavior, the returned coordinates/address are far away from the one I passed, not related to closer roads - roads that would reverse correctly if the coordinate I pass are closer to them.

See **Example A**
https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=39.441495&lon=-105.292625

returns  addresstype  "county" , name  "**Jefferson County**" with "lat":"39.5699803","lon":"-105.2561919" **(far away!)**

while **Example B**:
https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=39.457932&lon=-105.310821

returns  addresstype  "road" , name  "**South Wamblee Trail**" with almost  the same coords: "lat":"39.457819","lon":"-105.310792"

Now, I'm aware of the warning about reverse that _works by finding the closest suitable OSM object and returning its address information. This may occasionally lead to unexpected results._ (ref: [here](https://nominatim.org/release-docs/develop/api/Reverse/)) but in the above example the  "South Wamblee Trail" is much closer to the coordinates I passed in Example A. 

Why  Example A returns the address of an object that is much farther? It shoudl (at least) have returned the same of Example B.

Hope I was able to explain the issue - thanks for helping on sorting this one.

**Comment by lonvia** [comment]
This is intentional. The reverse call gives you a textual description of the coordinate you have entered, it is not a search for the closest road.

The Example A is in the middle of nowhere with no road nearby. So the best it can do for the description is to return the approximate area in which the point lies. In this example it is 'Jefferson County'. The coordinate returned is the centroid of Jefferson county. With a county being fairly large, the centroid tends to be far away.

`place_rank` gives you a hint about the kind of area Nominatim was able to place the coordinates. The [search rank table](https://nominatim.org/release-docs/develop/customize/Ranking/#address-rank) has an approximate translation of the number. The lower the number the less accurate the result.

**Comment by eliboni** [comment]
I see your point, I did not expect that since doc states Reverse _ works by
finding the closest suitable OSM object and returning its address
information_  it is the word "suitable" that has not a unique meaning!

So, I suppose there is no way to force returning always a road/building,
right?

Thanks

**Comment by lonvia** [comment]
With `zoom=18` you are guaranteed to get a building, if one is reasonably close. With `zoom=16` you get a street if there is (a named) one reasonably close. Forcing more than that does not make sense. In your Example A the closest road is one the other side of a ridge.

Simply check for the `place_rank` parameter and consider responses with a value smaller than 26 as 'no road in the vicinity' (or less than 29 for 'no building in vicinity').  That's exactly what a forced road/building response would do.

**Comment by eliboni** [comment]
That's sounds the way to do - @lonvia many thanks!
