### ISSUE TITLE
Reverse geocoding does not return amenities, only adresses

### ISSUE THREAD

**Issue by Juanjo-MC** [osm-search/Nominatim#2785]
## What did you search for?

https://nominatim.openstreetmap.org/reverse?lat=50.8973333&lon=4.3578048

## What result did you get?

The address of those coordinates

## What result did you expect?

I expected to see, in addition to the address, the name and info of the amenity located there (B Event caterer), see here: https://nominatim.openstreetmap.org/ui/search.html?q=B+Event
It seems to me that it worked that way before.

## Further details

May it be related to #2683, which is now solved?

**Comment by lonvia** [comment]
The house (with only the address) and the craft node are exactly the same distance from the lookup point. Which one of the two is returned is pretty much random. As soon as you are slightly away from the location of the craft node, the building polygon will always be closer.

**Comment by Juanjo-MC** [comment]
> The house (with only the address) and the craft node are exactly the same distance from the lookup point.

Not sure I understand. 
If you look at the reverse geocoding request I made, I passed to it the exact same coordinates than the forward one gave me for that POI. In that case the distance between the craft POI and the lookup point should be zero, no?

**Comment by lonvia** [comment]
> In that case the distance between the craft POI and the lookup point should be zero, no?

Yes it is. But so is the distance between the lookup point and https://www.openstreetmap.org/way/252972065. They are the same, namely 0. Thus whatever PostgreSQL decides to return first wins. We only order by distance and there is nothing in the query that would help decide which result should be preferred.

**Comment by lonvia** [comment]
I've given this some more thought and can't come up with any particular reason to chose one order over another. So lets approach this from another direction: @Juanjo-MC could you explain, why exactly it is a problem for you that the house is returned instead of the caterer? What were you trying to achieve?

**Comment by Juanjo-MC** [comment]
>  What were you trying to achieve?

Nothing in particular

> could you explain, why exactly it is a problem for you that the house is returned instead of the caterer? 

Well, it is not really a problem. I seem to remember that, in previous versions, if there was an amenity at the same address Nominatim was returning it. But it might be that I am wrong.

**Comment by lonvia** [comment]
We might have ordered by distance to the center of the building previously instead of the full building outline. But doing that comes with its own issues. One could argue that a node or a way should be preferred over an area when the distance is equal but that would only solve the case, where the location hits the amenity node exactly. Not too good either.

There are two related feature requests which could 'solve' this problem: #1469 asks to have a mode to return addresses only, which probably will be flexible enough to also have amenity-only. #1580 asks for multiple results, which would solve the issue by returning both amenity and address.

I'm closing this one as a "won't fix".
