### ISSUE TITLE
Reverse search /address/suburb is overwritten by /address/neighbourhood

### ISSUE THREAD

**Issue by cyberixae** [osm-search/Nominatim#2843]
I'm trying to retrieve the suburb and neighbourhood information with a reverse query. However, the suburb information gets overwritten by the neighbourhood information in the address breakdown of the response. The display name contains both, so the information is definitely available.

## What did you search for?

https://nominatim.openstreetmap.org/reverse.php?lat=60.21078&lon=25.07997&format=jsonv2

## What result did you get?
```
/address/neighbourhood: undefined
/address/suburb: Itäkeskus
```

## What result did you expect?

```
/address/neighbourhood: Itäkeskus
/address/suburb: Vartiokylä
```

OpenStreetMap has the correct information https://www.openstreetmap.org/query?lat=60.21078&lon=25.07997
The correct information is also present in the `/display_name` field of the reverse response

**Comment by lonvia** [comment]
That's because Itäkeskus was mapped as a suburb here: https://www.openstreetmap.org/node/3066460472

For more consistent address part information, I strongly recommend to use the [geocodejson](https://nominatim.org/release-docs/develop/api/Output/#geocodejson) format. Either use the `locality/district/city/county/state` fields, which try to be consistent over the entire planet. Or use the `admin` field if you are within a country and know exactly which `admin_level` you are interested in.

**Comment by cyberixae** [comment]
Ok. So the behaviour I was experiencing is perhaps not a bug then? I made some experiments with the `geocodejson` response format to see whether or not that would be more suitable. It sometimes gives me responses like
```
{
  type: "district",
  name: "small region",
  district: "big region"
}
```
I find it a bit confusing that both the small region and the big region are called `district`. Atleast this approach lets me extract both the name of the big region as well as the small region, so this is a clear improvement over the `jsonv2` response.
