### ISSUE TITLE
ICU tokenizer returning additional space during transliterate

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2909]
Default installation from master, no customization
```
$ nominatim --version
Nominatim version 4.2.0-0 (b607eb96)

$ nominatim search --query 'אסבל שכ א טור הר הזיתים'
Using project directory: /home/vagrant/nominatim-project
PHP Warning:  Uninitialized string offset 0 in /usr/local/lib/nominatim/lib-php/tokenizer/icu_tokenizer.php on line 131
```

Unicode inspect of the query
https://apps.timwhitlock.info/unicode/inspect?s=%D7%90%D7%A1%D7%91%D7%9C+%D7%A9%D7%9B+%D7%90+%D7%98%D7%95%D7%A8+%D7%94%D7%A8+%D7%94%D7%96%D7%99%D7%AA%D7%99%D7%9D

The query normalization in `makeStandardWord` transliterates `אסבל שכ א טור הר הזיתים` to `sbl sk  twr hr hzytym`. There are two subsequent spaces after `sk` which Github markdown might not render correct.

`SimpleWordList::__construct` documentation is clear that a normalized phrase is not expected to have two subsequent spaces.

The extra space means `extractTokensFromPhrases` produces
`sbl,sbl sk,sbl sk ,sbl sk  twr,sbl sk  twr hr,sbl sk  twr hr hzytym,sk,sk ,sk  twr,sk  twr hr,sk  twr hr hzytym,, twr, twr hr, twr hr hzytym,twr,twr hr,twr hr hzytym,hr,hr hzytym,hzytym` Note there is one empty token (two commas).

That breaks the search further. Fixing the printed PHP warning ("icu_tokenizer.php on line 131") is not enough.

Question is where the best fix is. Should we add logic that just removes subsequent spaces, e.g. in `makeStandardWord`?

**Comment by lonvia** [comment]
This needs fixing in the [transliteration rules](https://github.com/osm-search/Nominatim/blob/master/settings/icu_tokenizer.yaml#L19). Worst case it needs a fallback removing duplicate spaces. Sames as the final normalization rule https://github.com/osm-search/Nominatim/blob/b607eb9678c23a1063fb831e77aa7c7c34929c4e/settings/icu_tokenizer.yaml#L18

I'd rather find the root cause here though. Who exactly produces a space when transliterating a letter. That should not happen.

**Comment by lonvia** [comment]
So the culprit is the Aleph `א` as a single letter which gets deleted completely in transliteration.  Could somebody who knows Hebrew help out here? What does the query mean? Is the isolated Aleph meaningful here or is it just garbage that can be deleted?
