### ISSUE TITLE
Bad class/type in special phrases

### ISSUE THREAD

**Issue by geoneutrino** [osm-search/Nominatim#2914]
Minor bug/informative
Importing special phrases shows errors

Importing phrases for lang: pl...
Bad class/type: shop=. It will not be imported
... (6 times)
6 phrases were invalid and have been skipped during the whole process.

Code points to sp_wiki_loader.py
https://wiki.openstreetmap.org/wiki/Special:Export/Nominatim/Special_Phrases/PL
contains part
... Sklep || shop || || - || N |- | Sklepy || shop || || - || Y |- | Sklep w || shop || || in || N |- | Sklepy w || shop || || in || Y |- | Sklep przy || shop || || near || N |- | Sklepy przy || shop || || near || Y |- | Postój taksówek  ...
these seem to be the 6
So either the wiki xml generation should filter these or the import should handle this different/ignore ?

Nominatim 4.2 release but was also in the 4.1

**Comment by lonvia** [comment]
As the message informs you, the phrases have been ignored on import. What else do you expect to happen?

**Comment by geoneutrino** [comment]
if its ok from a technical point of view you can close the issue
i thought there is a problem in the special phrases xml ...

**Comment by lonvia** [comment]
There is a problem with the table in the wiki being incorrectly filled. This is something that will happen from time to time because the wiki can be edited by anybody. The import code takes that into account. You can fix the errors in the wiki if you like (by deleting the offending entries) to get rid of the notice.
