### ISSUE TITLE
Additional reference tags to import

### ISSUE THREAD

**Issue by PinkDuck** [osm-search/Nominatim#295]
Consider adding unsigned_ref, official_ref and admin_ref. These are typically used for council road references to C and D roads, typically highway=tertiary. It would be useful to search on these for when they are mentioned in official announcements (newspaper/web).

**Comment by lonvia** [comment]
Why three different versions? Can't you agree on one ref tag?

**Comment by PinkDuck** [comment]
My own preference is just for the ref tag to be used with ref:signed=no. Those other ones were proposed and are in various levels of use. If no reference is found from your existing lengthy list of tags, I don't see much harm in scanning for three more reference-like tag aliases.

**Comment by lonvia** [comment]
There is harm because it never ends with just three tags. Next, somebody wants semi_official_ref, then municipal_ref etc. For a new tag to be considered I would expect that there is a) a sufficient consensus in the (sub)community on its use, b) a wiki page, c) a good reason why current tags don't cover the use.

**Comment by lonvia** [comment]
I'm closing this. You can add additional flavours of ref tags now in your own instance via the style files. There are no plans to add these tags to the default style.
