### ISSUE TITLE
Albany, New York / name:etymology:wikipedia

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2950]
## What did you search for?

Albany, New York
https://nominatim.osm.org/ui/search.html?q=Albany%2C+New+York

## What result did you get?

Albany Avenue, Hartford, Connecticut
https://www.openstreetmap.org/way/657687638

## What result did you expect?

City of Albany https://www.openstreetmap.org/relation/175549
Albany is the capital city of the state of New York. https://en.wikipedia.org/wiki/Albany,_New_York

## Further details

The only <name of capital city, name of state> combination in the US that doesn't return the correct city.

I think the address keyword comes from the `name:etymology:wikipedia=en:Albany, New York` value. The road has been last edited 10 months ago.

https://github.com/osm-search/Nominatim/issues/2933#issuecomment-1367440289 says `name:etymology:wikipedia` is already excluded but I can't see that in
* the old style file https://github.com/osm-search/Nominatim/blob/200eae3bc0b559e7df7c1d1fb50141830c2f1849/settings/import-extratags.style 
* new lua based style file https://github.com/osm-search/Nominatim/blob/200eae3bc0b559e7df7c1d1fb50141830c2f1849/settings/import-extratags.lua

(not sure which one was active when this place was indexed)

The tag is used 58.842 times https://taginfo.openstreetmap.org/keys/name:etymology:wikipedia 55.925 of those in combination with `highway` tag.

**Comment by lonvia** [comment]
https://github.com/osm-search/Nominatim/commit/56f0d678e3fb361f8211e5ee12c963a8f6f013fe excludes the `:wikipedia` suffixes (which I could have sworn has been there when I last checked).

The issue here is a bit more wider though and concerns names with comma in general. This is not the first time a comma-separated term was causing issues. I wonder if we need to review the decision to blindly split terms on commas. A name like `albany, new york` should never have a full-name match on `new york`. Looking through example where commas are used in names, that's true for most names with commas. There are gems like the [Honorable Hannah Diggs Atkins, Secretary of State, Memorial Highway](https://www.openstreetmap.org/way/282442910) which you find when searching for [secretary of state](https://nominatim.openstreetmap.org/ui/search.html?q=secretary+of+state). Makes no sense.

**Comment by lonvia** [comment]
Comma as separator removed in #2954. This will only have an effect after data is changed in OSM on the public instance.
