### ISSUE TITLE
CLI nominatim details reports "Integer number expected for parameter 'osmid'"

### ISSUE THREAD

**Issue by mtmail** [osm-search/Nominatim#2951]
Can probably wait until after the PHP->Python migration

```
nominatim details --way 518071791
{"error":{"code":400,"message":"Integer number expected for parameter 'osmid'"}}

nominatim details --w 518071791 --osmid 518071791
nominatim: error: unrecognized arguments: --osmid 518071791

nominatim details --way --osmid 518071791
nominatim details: error: argument --way/-w: expected one argument

nominatim --version
Nominatim version 4.2.99-0 (5f4e98e0) # aka master
```

**Comment by lonvia** [comment]
I noticed that typo while working on the new Python details code at https://github.com/osm-search/Nominatim/blob/5f4e98e0d9b5e89c81bc09a53cfdba1bdb45351b/nominatim/clicmd/api.py#L254-L256

It's fixed in the upcoming Python implementation but I've pushed a fix for the old code now anyway. This way the fix can be backported if we do a minor release before the next major one.
