### ISSUE TITLE
Consider using Wikipedia article names as final backup

### ISSUE THREAD

**Issue by matkoniecz** [osm-search/Nominatim#2969]
## What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=Pi%C5%82sudski%27s+Mound
https://nominatim.openstreetmap.org/search.php?q=Pi%C5%82sudski%27s+Mound&format=jsonv2&debug=1

## What result did you get?

> No search results found

## What result did you expect?

https://www.openstreetmap.org/node/274386820

## Further details

https://en.wikipedia.org/wiki/Pi%C5%82sudski%27s_Mound is indirectly linked via `wikipedia` and `wikidata` tags

I searched for similar issues and have not found anything, hopefully I have not missed anything this time.

Note: I am not 100% sure is there some licensing complication, I admit that I have not researched this aspect situation strongly enough to be sure.

**Comment by lonvia** [comment]
This is not going to happen at least not on the  official instance. Nominatim is explicitly there for searching in OSM data. Adding Wikipedia names would just cause confusion.

We do need to do something in terms of translated category terms, see my thoughts on that in #2944. However, I don't think that any solution there will ever cover this particular case because 'mound' wouldn't really be covered by `natural=peak` (among other things, there is nothing natural about it). `historic=monument` would need a subtag that describes the 'mound type'. But this is a tagging discussion that does not belong here.
