### ISSUE TITLE
Search fails when trying to return large geometries

### ISSUE THREAD

**Issue by ghost** [osm-search/Nominatim#2987]
## What did you search for?

Groot-Brittannië, United Kingdom

## What result did you get?
Status code 500

## What result did you expect?
The result of the search

**Comment by mtmail** [comment]
https://nominatim.openstreetmap.org/search.php?q=Groot-Brittanni%C3%AB%2C+United+Kingdom&format=jsonv2 works for me.

Can you list the full URL or other instructions to reproduce the error?

**Comment by Romeo-PHILLIPS** [comment]
Just calling it inside the search window on https://nominatim.openstreetmap.org/ui/search.html makes it error out:

<img width="1030" alt="Capture d’écran 2023-02-20 à 10 34 59" src="https://user-images.githubusercontent.com/92714362/220067787-9cd49012-7121-4e37-a985-a628f7f6f565.png">

**Comment by mtmail** [comment]
Ok, I see, it’s the polygon part of the request that is causing it

https://nominatim.openstreetmap.org/search.php?q=Groot-Brittanni%C3%AB%2C+United+Kingdom&format=jsonv2&polygon_geojson=1

returns

{"error":{"code":500,"message":"Allowed memory size of 209715200 bytes exhausted (tried to allocate 20480 bytes)"}}

**Comment by lonvia** [comment]
You are trying to retrieve extremely large geometries. This does not work with the public servers. We have to protect our infrastructure. You can alleviate the situation by using the `polygon_threshold` parameter.

We probably should build something in that simply ignores the `polygon_*` parameters for large geometries. Not sure if PostGIS can given an estimate of geometry size.

**Comment by lonvia** [comment]
Oh, [ST_MemSize](https://postgis.net/docs/ST_MemSize.html) will do the trick. I shall add a cut-off to the new frontend implementation.

**Comment by Romeo-PHILLIPS** [comment]
> You are trying to retrieve extremely large geometries. This does not work with the public servers. We have to protect our infrastructure. You can alleviate the situation by using the `polygon_threshold` parameter.

And is there a setting to enable a custom instance to return the results without adding a parameter inside the request?

**Comment by lonvia** [comment]
No, there is no setting. You can increase the hard-coded memory limits on your instance, e.g. https://github.com/osm-search/Nominatim/blob/8191c747b964530f67b064b43954e13a5b1a0791/lib-php/website/search.php#L15

That will get rid of the error, when the geometry is large.

To change the default for the threshold, you need to change the code at https://github.com/osm-search/Nominatim/blob/8191c747b964530f67b064b43954e13a5b1a0791/lib-php/PlaceLookup.php#L30

**Comment by lonvia** [comment]
The new Python frontend has a much more memory-efficient way of handling geometry, so that usually there shouldn't be an error anymore. You will still see it occasionally when the server is under high load and Postgres cannot get the geometry fast enough but this is more an operational necessity specifically for nominatim.openstreetmap.org.

Looking at the database where the big geometries are, it turns out that this does not concern administrative boundaries. The biggest country boundary is only 3MB (4.5MB as GeoJSON). The problematic ones are forests, lakes, islands, etc. We don't need exact geometries of these features as they are not used for addresses. The geometries might as well simplified already when added to the database. Between 100 and 400 geometries would be affected, depending on where the cut-off is.
