### ISSUE TITLE
Not clear how to get a village from reverse search

### ISSUE THREAD

**Issue by akamuza** [osm-search/Nominatim#3009]
## What did you search for?
It's hard to get a correct village in a reverse search for coordinate: [51.817, 25.0457](https://www.openstreetmap.org/#map=15/51.817/25.0457) 

Zoom level 12/13 (Town/Village): https://nominatim.openstreetmap.org/reverse?lat=51.8170&lon=25.0457&zoom=12

## What result did you get?
For zoom level 13,12 I get municipality **Kamin-Kashyrskyi Urban Hromada**

## What result did you expect?
The result should be the village **Velyka Hlusha**

## Further details
As a workaround, I can use zoom 14 (neighborhood) https://nominatim.openstreetmap.org/reverse?lat=51.8170&lon=25.0457&zoom=14 
and get the neighborhood (**Яновка**) in this village as a result: `"addresstype": "neighbourhood"`. And then there is the village in address.

But it seems it should be possible to look for villages, towns specifically without need to interpolate from a neighborhood.

Another example: https://nominatim.openstreetmap.org/reverse?lat=50.690123&lon=24.462326&zoom=12
Should be **Oryshchi**, but returns **Pavlivka Rural Hromada**.

Maybe some kind of _filter_ could be applied to reverse search to restrict results only to a certain type?

Or am I confusing zoom levels presuming 14 as neighborhood and 13/12 as village/town ?

**Comment by lonvia** [comment]
The zoom levels are a little bit oddly chosen, possibly because they weren't adapted when we cleaned up the internal rank levels. zoom=12/13 goes only down to 'town' while the next one zoom 14 already goes to level suburb.

I think we can risk to modify the ranks for zoom=13, so that it includes villages and hamlets. A quick llok at server statistics shows that only 0.1% of requests use the zoom level, so that the damage should be minimal. There is a similar issue for zoom=15 which should go down to locality level.
