### ISSUE TITLE
No search results for known POIs

### ISSUE THREAD

**Issue by octavo** [osm-search/Nominatim#3032]
[toilets cph], [defibrillator cph], [postbox cph] produce few or no search results.

**Comment by mtmail** [comment]
You will get more help if you add a lot more detail and examples to your report. Use the " Report issues with search results" template on https://github.com/osm-search/Nominatim/issues/new/choose Read the "special phrases" part of the https://nominatim.org/release-docs/latest/api/Search/ documentation.

**Comment by GeorgV** [comment]
This is a requirement to identify "important" locations of commonly used objects in the search. 
A short test of the three keywords showed that they are only found if these terms also appear in the key name. This is an error in the database rather than a hit.
Should this be realised, the data load would probably have to be supplemented by amenity=toilets, amenity=post_box, emergency=defibrillator. In addition, the translation of the keys (toilet, toilette, λεκάνη, शौचालय) would have to be elicited via Wikidata so that they are not identified as name components but as object descriptions (as is presumably already done for shops).
@octavo I ask for a short confirmation if my analysis is correct.

**Comment by lonvia** [comment]
Your query would be looking for all toilets/defibrilators/postboxes in Copenhagen. This is not something Nominatim will ever support. For systematic downloading of POIs in a larger area use Overpass API. If you meant to look for toilets in Copenhagen Airport, then searching [exactly for that phrase](https://nominatim.openstreetmap.org/ui/search.html?q=toilets+in+copenhagen+airport) works fine. 

Other than that, I point to all the other issues which discuss search by category name (aka special phrases in Nominatim) and repeat what was said there: support for 'special phrases' or category searches is extremely limited with Nominatim. This might change at some point in the future, so that detection of category searches works better and produces more meaningful results but it will never go so far as producing complete list of POIs. Again, use Overpass for that.

**Comment by octavo** [comment]
[toilets in cph] and [defibrillators in cph] seem to work, but not [toilets/defibs cph].

**Comment by mtmail** [comment]
That's expected and part of the documentation, see the "special phrases" part of the https://nominatim.org/release-docs/latest/api/Search/ page
