### ISSUE TITLE
Search for the country "Dominica" returns info for "Dominican Republic"

### ISSUE THREAD

**Issue by lizfrank** [osm-search/Nominatim#3042]
## What did you search for?

https://nominatim.openstreetmap.org/ui/search.html?q=dominica

## What result did you get?
A boundary box and information for the country "Dominican Republic".  A second option for "Dominica" is listed, but is not the primary result.

## What result did you expect?
A boundary box and information for the country "Dominica" as the primary result.

**When the result in the right place and just named wrongly:** 

**When the result missing completely:**

**Comment by lizfrank** [comment]
Is there a way to specify which language to use to match the country name?

**Comment by lizfrank** [comment]
The details of the country "Dominica" list the name correctly as the first entry and as the English name, with no accent or stress characters:
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=307823&class=boundary

How do I tell Nominatim to use only the English name to return the country code?

**Comment by lonvia** [comment]
After giving it some thought, I'm closing this as a data issue. The Talossian names shouldn't have been in the database in the first place. I'd appreciate help in removing them but it might be better to send a short notice to https://community.osm.org before doing that.

It's very difficult to change the reranking algorithm to make Dominica appear in the first place without making a lot of other results worse because this is a perfect match against one of the names of the country after all. So it is a won't fix in that sense.

If you run your own database, you can (and probably should) block the names by adding `*:tzl` to the list of deleted tags. (See [Import styles](https://nominatim.org/release-docs/latest/customize/Import-Styles/) for more information on custom styles.) I won't do that for the main instance at https://nominatim.openstreetmap.org because this is the instance for mappers and it's purpose is to show-case all data including the slightly odd parts. So if you use this instance, you need to do your own post-filtering of search results to remove results that do not match the English name variant.
