### ISSUE TITLE
psycopg2.OperationalError: terminating connection due to idle-in-transaction timeout

### ISSUE THREAD

**Issue by MALKARAJ** [osm-search/Nominatim#3083]
psycopg2.OperationalError: terminating connection due to idle-in-transaction timeout

**Describe the bug**

![error in nominatim](https://github.com/osm-search/Nominatim/assets/62066377/c6eeacaf-7371-4580-aaaf-1cbe4ae9c68b)
Replication type continuous
once replication update is completed it goes for a sleep, this error/exception is happening after this

**To Reproduce**
once replication(type continuous is completed)  this issues will happen

**Software Environment (please complete the following information):**
Nominatim version 4.2.3
postgres 10.3
postgis: 2.5.9
OS: Ubuntu 22.04.2 LTS

**Hardware Configuration:**
- RAM:  8GB
- number of CPUs: 64CORE
- type and size of disks: 266GB

**Comment by lonvia** [comment]
So, leaving the connection open while sleeping for 15 hours may not be the best of ideas. The reason you got this error was because something happened to the database in between. Either it was restarted or it just closed the connection due to an internal timeout. Both are of course entirely reasonable things to happen.

Fix is no the way. In the meantime I would recommend to avoid the use of continuous updates. systemd is doing a much better job at regularly running the updates these days. Please refer to https://nominatim.org/release-docs/latest/admin/Update/#one-time-mode-with-systemd for details on how to set this up.
