### ISSUE TITLE
County parameter issue

### ISSUE THREAD

**Issue by t0mmy9** [osm-search/Nominatim#3136]
## What did you search for?

https://nominatim.openstreetmap.org/search?country=gb&addressdetails=1&format=json&q=downing%20street%20england

## What result did you get?

No street results.

## What result did you expect?

List of GB street matches

## Further details

We use Nominatim for UK street lookups (thank you for providing this great service!) but I have just noticed that adding "country=gb" to the URL no longer appears to work.

So this fails:
https://nominatim.openstreetmap.org/search?country=gb&addressdetails=1&format=json&q=downing%20street%20england

But this is ok:
https://nominatim.openstreetmap.org/search?addressdetails=1&format=json&q=downing%20street%20england

The documentation doesn't mention country no longer being valid:
https://nominatim.org/release-docs/latest/api/Search/

Or should we be using countrycodes instead?

https://nominatim.openstreetmap.org/search?countrycodes=gb&addressdetails=1&format=json&q=downing%20street%20england

**Comment by mtmail** [comment]
See "Do not combine with q=<query> parameter." in the documentation https://nominatim.org/release-docs/latest/api/Search/

**Comment by otbutz** [comment]
https://nominatim.openstreetmap.org/search?countrycodes=gb&addressdetails=1&format=json&q=downing%20street

or even better:

https://nominatim.openstreetmap.org/search?country=gb&street=downing+street&addressdetails=1&format=json

As @mtmail pointed out:

* generic parameter for unstructured and structured search: countrycodes
* structured search parameter: country

**Comment by mtmail** [comment]
I forgot the "no longer appears to work" part of the question. One of the servers is running an unreleased version of Nominatim, a big rewrite. This week we're seeing some bug reports where users relied on undocumented behaviour. So it's possible Nominatim will soon be more strict with the country parameter than it has in the past.

**Comment by t0mmy9** [comment]
Ha! Sorry I missed the bold "Do not combine with q= parameter." This can be put down to user error, I will close this issue thanks for everyone's help.

**Comment by lonvia** [comment]
Nominatim would simply ignore the structured parameters until recently when a 'q' parameter was present. Then somebody started to send a massive amount of queries like that: `q=234 main st&city=Dodge City&state=NA` So the effective search was just for a housenumber and street name, which is really expensive when the street name is frequent enough. You'd expect that the caller would soon enough realise that they get random results instead of results in the city they are looking for. But no, they continued for weeks. So I did an emergency fix that turns around the logic and ignores the 'q' parameter when a structured parameter is present, at which point your queries broke.

Thinking some more about this, it is better to simply return an error when parameters are mixed. The result will always be surprising when using mixed parameters and it's better to inform the user that there is an error on their end.
