### ISSUE TITLE
City/County rank ordering differences

### ISSUE THREAD

**Issue by ZeLonewolf** [osm-search/Nominatim#3195]
I've noticed that certain searches return results in a different order when a city and county have the same name.

## What did you search for? / What result did you get?

Search: **Providence, RI** [link](https://nominatim.openstreetmap.org/ui/search.html?q=providence%2C+ri)
Results:
Providence (the city)
Providence County

Search: **Newport, RI** [link](https://nominatim.openstreetmap.org/ui/search.html?q=newport%2C+ri)
Results:
Newport County
Newport (the city)

## What result did you expect?

City and county results appear in the same order. I expect to find the city to be the first result and the county to be the second result.

**Comment by lonvia** [comment]
If the result order is odd, then this is pretty much always due to a bad wikipedia/wikidata tag in the OSM data. Nominatim orders by wikipedia article link prominence which pretty much always favours the city over the county.

In the case of Newport we have the county node https://www.openstreetmap.org/node/316987972 with a wikipedia/wikidata tag that points to the page of the city. Order should be better after fixing that.
