### ISSUE TITLE
Hamlet of Pine Island, NY should always be on top of result list

### ISSUE THREAD

**Issue by rainbowoflight** [osm-search/Nominatim#3288]
## What did you search for? **Pine Island, NY**

 
https://nominatim.openstreetmap.org/ui/search.html?q=pine+island%2C+ny+usa

## What result did you expect? If all 9 were provided to choose from, then the confusion would have been quickly resolved.  **See detailed discussion at OpenStreetMap.org Community Forum** 
https://community.openstreetmap.org/t/map-look-up-pine-island-ny-on-12-27-2023-was-correct-map-look-up-same-on-12-29-2023-not-so-correct/107588/4

**When the result in the right place and just named wrongly:** No

 **Pine Island, New York, Town of Warwick, Orange County**

**When the result missing completely:** **No**

## Further details
**I entered all the links, details, screen shots etc in the community forum at Open Street Map:**
https://community.openstreetmap.org/t/map-look-up-pine-island-ny-on-12-27-2023-was-correct-map-look-up-same-on-12-29-2023-not-so-correct/107588

**Who would have expected 9 counties in New York State to have a Pine Island? ....  Smile**

**Sorry I cannot be helpful, not an experienced Tech.**

**Comment by mtmail** [comment]
If I understand correct you expect the hamlet "Pine Island, Town of Warwick, Orange County, New York" (https://www.openstreetmap.org/node/158811996) to be the top result. The other 8 results are of type island or islet and less relevant. Nominatim search engines give a little boost if the type of a place is part of the query, that's why some islands might be listed higher than expected.

**Comment by rainbowoflight** [comment]
Thank you mtmail  for your response.  

My search on 12/27/2023, gave me the Pine Island in Warwick Town where I was traveling.  On 12/29/2023, the result was in between Fort Drum and Adirondack Park.  So I tried a few times getting the same.  

I had no idea there were 9.  I was rushing to double check the directions for my travel.  Therefore I was not swift enough at the time to enter Town of Warwick.  The result confused me.  

I did not see anything that would have let me know there were several Pine Islands.  I just thought the map had been modified and it was now incorrect. 

Therefore I reached out to the community forum.  Ha!  I was surprised by the actual results, a learning curve.  But some other semi-non-geek would just give up on Open Street Map all together.

**Comment by lonvia** [comment]
I've responded in the [forum](https://community.openstreetmap.org/t/map-look-up-pine-island-ny-on-12-27-2023-was-correct-map-look-up-same-on-12-29-2023-not-so-correct/107588) to reach a wider audience. To repeat here:

You likely got different results on different days because you were looking at different parts of the map when you were searching. There is a small bias towards places that are in or near the currently visible part of the map. They tend to appear higher in the result list.

That said the other results are all minor islands or islets. They currently get far too much importance when deciding the order of results. Improving that is already high on the todo list. The hamlet really should be on the top of the list most of the time.

I'll keep the ticket open as a reminder for the importance tweeking. I've adopted the title accordingly.

**Comment by rainbowoflight** [comment]
Dear Sarah Hoffmann,
Thank you very much for sending me a note. I very much care that people obtain benefit from Open Street Map, thus I took the time.
I appreciate learning to become more computer wise.
Thanks again, and Happy Healthy 2024.
All the Best,
Lynn

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by lonvia** [comment]
The default importances are now adapted, see #3346. The islands will still be preferred when they are in the viewbox but at least the hamlet will show up first in all other cases.

Note that you cannot see these changes on nominatim.openstreetmap.org yet because the adaption of the importances requires a reimport/updates.
