### ISSUE TITLE
Python frontend takes long time to processes certain queries and returns 500 error to the user

### ISSUE THREAD

**Issue by pawel-wroniszewski** [osm-search/Nominatim#3303]
## What did you search for?
9 k https://nominatim.openstreetmap.org/search.php?q=9+k&format=jsonv2
9 al https://nominatim.openstreetmap.org/search.php?q=9+al&format=jsonv2
6 al https://nominatim.openstreetmap.org/search.php?q=6+al&format=jsonv2
10 ju https://nominatim.openstreetmap.org/search.php?q=10+ju&format=jsonv2
10 ji https://nominatim.openstreetmap.org/search.php?q=10+ji&format=jsonv2
1 h https://nominatim.openstreetmap.org/search.php?q=1+h&format=jsonv2
1 al https://nominatim.openstreetmap.org/search.php?q=1+al&format=jsonv2
1 s https://nominatim.openstreetmap.org/search.php?q=1+s&format=jsonv2
12 r https://nominatim.openstreetmap.org/search.php?q=12+r&format=jsonv2
5 ba https://nominatim.openstreetmap.org/search.php?q=5+ba&format=jsonv2

## What result did you get?
500 Internal Server Error

## What result did you expect?
A proper result or an empty list. If queries take too long, I'd expect them to be terminated and a non-complete result set be returned to the user, according to the NOMINATIM_REQUEST_TIMEOUT docs. 

## Further details

I think the 500 error is the QUERY_TIMEOUT error being propagated to the user. 
I was playing with Python frontend compiled from current master (bfc7acb) and I get the same. They work when I increase the QUERY_TIMEOUT. The queries can take up to a minute on my machine. Surprisingly, they take that long every time I run them - I'd expect them to be cached in Postgres once complete.

**Comment by lonvia** [comment]
The queries hit the [NOMINATIM_QUERY_TIMEOUT](https://nominatim.org/release-docs/latest/customize/Settings/#nominatim_query_timeout), where the documentation correctly states that an error will be returned. This is intentional because it is meant to indicate to the user that the queries they are sending are bad and should not be continued in this way. For example, the queries you list above suspiciously look like search-as-you-type queries which are not supported by Nominatim and  forbidden by the [nominatim.osm.org usage policy](https://operations.osmfoundation.org/policies/nominatim/).

That all said, it still should be returning a 503, not a 500. I think something goes wrong with error translation in the falcon glue code.

**Comment by pwronisz** [comment]
I see. We get such queries from our clients. Should it be possible to set the NOMINATIM_REQUEST_TIMEOUT to a lower value than NOMINATIM_QUERY_TIMEOUT to return an empty result set (as the docs say) instead of an error? I think it would be more user friendly, but I tried that and it didn't work. 
503 error indicates that there's an issue with the server, I don't think it's a proper way to indicate to a client that there's an issue with the query in the request. 400 error would carry such message better.

**Comment by mtmail** [comment]
I believe HTTP 503 is correct, it means "The server cannot handle the request (because it is overloaded or down for maintenance). Generally, this is a temporary state." The client should try again.

HTTP 400 would indicate the client made a mistake and should change something (different URL parameters, send less data or such) before retrying. That's not the case though.

**Comment by lonvia** [comment]
NOMINATIM_QUERY_TIMEOUT and NOMINATIM_REQUEST_TIMEOUT are very different errors internally. The former is a exceptional condition, the latter just restricts the number of SQL queries that Nominatim will try for giving up. The two configuration parameters are completely independent.

I'd consider the QUERY_TIMEOUT still a 503 because it is still a server issue in the sense that Nominatim shouldn't be creating SQL code that takes so long. It's not really temporary but there is no good other server timeout error that describes a permanent state. I was tempted to send a 418 back but I can see how that would create an endless stream of support requests. If you don't like the 503 in your server you can change it [here for falcon](33c0f249b1a9bc716bcb89078c4a766766cbe94f) or [here for starlette](https://github.com/osm-search/Nominatim/blob/33c0f249b1a9bc716bcb89078c4a766766cbe94f/nominatim/server/starlette/server.py#L125).

After adding some means of debugging the 503 requests, I believe I have identified the problem. The search index has grown to such a size that PostgreSQL attempts a sequential scan on the search_name table in some conditions. 33c0f249b1a9bc716bcb89078c4a766766cbe94f will hopefully improve the situation for the example queries in this issue.

**Comment by pawel-wroniszewski** [comment]
I am happy to report that the issue is indeed fixed. I also had a few other queries which were previously failing in my local deployment and now they work: "montgomery a", "University a", "Melbourne A". Thanks!
