### ISSUE TITLE
County information for certain New York boroughs not available in API, but are visible in UI

### ISSUE THREAD

**Issue by patelmm79** [osm-search/Nominatim#3485]
## What did you search for?

[<!-- Please try to provide a link to your search. You  can go to https://nominatim.openstreetmap.org and repeat your search there. If you originally found the issue somewhere else, please tell us what software/website you were using. --https://nominatim.openstreetmap.org/lookup?&osm_ids=R9691750&format=json&extratags=1&namedetails=1&accept-language=en

## What result did you get?
no county fielld

## What result did you expect?
county field = Kings county, per info in UI

https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=9691750&class=boundary
**When the result in the right place and just named wrongly:** 

## Further details

Locations in Queens, Bronx, Staten Island also appear to be affected. Manhattan, however, is not (county is correctly populated as "New York County"

https://nominatim.openstreetmap.org/lookup?&osm_ids=R8398124&format=json&extratags=1&namedetails=1&accept-language=en

**Comment by mtmail** [comment]
Large metropolis cities like New York, London, Paris are a challenge. Part of those cities are cities themselves and they come up with new names to divide themselves (e.g. quarters or Manhattan Community Boards).

The issue here is that Manhattan is the common name of the county 'New York County' but users expect a place to be inside a county (of itself). I'll have a look later with more time but I expect half the problems are with the OSM data itself and touching anything in New York can upset the local mappers there. See the long discussion at https://community.openstreetmap.org/t/manhattan-community-boards-as-administrative-boundaries/115549 for example.

At least the OSM data for `admin_level=6` seems to be complete and not broken. https://overpass-turbo.eu/s/1OFG

**Comment by mtmail** [comment]
I had another look but it hasn't gotten clearer. King's County seems to have a Norwegen Wikipedia page attached but I can't find where that value originally came from (in OSM data history) https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=369518&class=boundary It's also weird that the county has a 'type=label' relation member that points to the same Brooklyn node as Brooklyn.

A work-around is to use the `geocodejson` output format https://nominatim.openstreetmap.org/lookup?&osm_ids=R9691750&format=geocodejson&extratags=1&namedetails=1&accept-language=en
```
          "label": "Brooklyn, Kings County, New York, United States",
          "name": "Brooklyn",
          "district": "Kings County",
          "city": "New York",
          "state": "New York",
          "country": "United States",
          "country_code": "us",
          "admin": {
            "level7": "Brooklyn",
            "level6": "Kings County",
            "level5": "New York",
```

The `json` and `jsonv2` formats select one of level6 and level7 and it seems in case of New York boroughs the wrong one.

**Comment by lonvia** [comment]
The Norwegian wikipedia page is easily explained from the Wikidata tag. King's county only seems to have wikipedia pages in the Norwegian and Hungarian version. Everybody else just forwards to the Brooklyn article. This is all just as it should be. The King's County boundary gets a much lower importance because of that.

The guilty party here is indeed the link to the place=suburb node in both relations. a label member in the relation means that the boundary inherits the place type from the label member. Thus, we now have a suburb "Brooklyn" and a suburb "King's County". When formatting the output, Nominatim is rightfully confused and decides to drop "King's County" as a mapping error. Remove the label member in the county and things will be fine.

I wonder if using the same node as label in different relations is something we should flag in https://nominatim.org/qa.

Unrelated comment: I think `alt_name=Brooklyn` for King's County is just wrong as well. Either Brooklyn is an alternative name, then the Brooklyn relation shouldn't exist or it's two different entities and then it isn't an alt_name.

**Comment by patelmm79** [comment]
I think the classification of Brooklyn , Queens etc. as "suburbs" is a bit
strange, as is putting "Kings county" as the district.

King's county is the county, and Brooklyn is probably best described as the
"city district".

**Comment by lonvia** [comment]
Closing here as data issue.
