### ISSUE TITLE
type=postcode's bounding box is small/NULL

### ISSUE THREAD

**Issue by drzraf** [osm-search/Nominatim#719]
Results of type postcode's bbox is not correct from what I can't tell.

* For a city areas (districts having a "sub-postal code") it brings results of node, ways or relation  ... but nothing like a _type=administrative_
Sometimes, it only return way/node but nothinkg like a "_osm_type=relation_"
https://nominatim.openstreetmap.org/search?format=json&limit=5&countrycodes=fr&polygon_geojson=0&accept-language=fr_FR&postalcode=13004

* But for small city too (no district number):
There is one result, a place of _type=postcode_ (no osm_type), but the bounding box (best zoom-level) is NULL (bbox of a point)
https://nominatim.openstreetmap.org/search?format=json&limit=5&countrycodes=fr&polygon_geojson=0&accept-language=fr_FR&postalcode=55000
(geojson contains a Point())

This applies identically for _postalcode=XXXXX_ or _q=XXXXX_ , it's all about the resulting data.
This is annoying because postalcode are a zone-specification rather than a point-specification but having only PoI in the results does not let one render map bounds as they should.

**Comment by lonvia** [comment]
The kind of result is intended. Searching for a postcode returns you the (artifical mostly) postcode object and its computed address, not the administrative area, mostly because there is no reliable way to find the correct area. The only exception would be when post code areas are mapped in OSM. These should be returned in preference and that does not always happen, e.g. http://nominatim.openstreetmap.org/search.php?q=69214%2C+germany. So there is something to improve.

The empty bbox is not correct. Postcode nodes should have a small bbox like all other nodes.

**Comment by drzraf** [comment]
Do know how to help pushing forward this issue?
I'm not used with OSM concept and uses of "tags" and have little time, but if you're sure it's a bug [in](https://github.com/openstreetmap/Nominatim/blob/master/lib/lib.php) the [code](https://github.com/openstreetmap/Nominatim/blob/master/lib/PlaceLookup.php), then I may try to give it a look.

**Comment by lonvia** [comment]
I'm in the process of completely rewriting the postcode code. This issue will be fixed as part of the rewrite.

**Comment by lonvia** [comment]
The bounding box is not empty, it is just very small.

**Comment by lonvia** [comment]
Doesn't seem to be an issue anymore.
