### ISSUE TITLE
Changing the limit parameter impacts search result order

### ISSUE THREAD

**Issue by christophfriedrich** [osm-search/Nominatim#882]
**Case:**
When I search for `street=Schillerstraße 43&city=Münster` with `limit=5` [(link)](https://nominatim.openstreetmap.org/search?format=json&limit=5&street=Schillerstra%C3%9Fe%2043&city=M%C3%BCnster), the first result is that street in the city of Münster (correct result). I get an additional 4 matches with the same street name elsewhere as result 2-5.
Now I search for the same criteria with `limit=1` [(link)](https://nominatim.openstreetmap.org/search?format=json&limit=1&street=Schillerstra%C3%9Fe%2043&city=M%C3%BCnster), so that I get only 1 result.

**Expected behaviour:**
The only result being returned is the first result of the previous request (i.e. results 2-5 of the previous request are removed).

**Real behaviour:**
The only result being returned is not the first, but the second result of the previous request.

**Problem:**
Changing the limit parameter should not impact search result order.

*mtmail: I edited the first URL because it contained limit=1*

**Comment by mtmail** [comment]
Observation: same happens for unstructured queries. 

https://nominatim.openstreetmap.org/search?format=json&limit=5&q=Schillerstra%C3%9Fe%2043,%20M%C3%BCnster
https://nominatim.openstreetmap.org/search?format=json&limit=1&q=Schillerstra%C3%9Fe%2043,%20M%C3%BCnster

**Comment by lonvia** [comment]
This is not fixable in general. The final order of the results is determined after the requested number of results have been retrieved from the database. And the criteria for ordering are slightly different than the order in the database.

However, for this particular case, I'm thinking that the address importance that determines the final order (Münster is better known than Gelsenkirchen) might be added to the place importance, so that we already get the better ordering in the database.

**Comment by PhilHamm** [comment]
this seems to happen regularly when the correct address isn't available on house number granularity.

E.g.
https://nominatim.openstreetmap.org/ui/search.html?street=Mainstra%C3%9Fe+8&city=Bamberg&country=Deutschland&postalcode=96052 (list of results with correct street on first position)
https://nominatim.openstreetmap.org/ui/search.html?street=Mainstra%C3%9Fe+8&city=Bamberg&country=Deutschland&postalcode=96052&limit=1 (any Mainstraße 8 with wrong postal code and city)

after mapping the house number, this would work (verifiable with house number 10 instead of 8). I've faced some further examples with many 100km deviation.

<br>

Wouldn't it be possible to provide a query which retrieves all results from the database but the api only returns the best result (also in regard to reliability)?

Of course I could just change my code to always query for the whole list and just keep the first entry - but this seems to be a common pitfall a lot of people will discover (or they'll never discover and work with the wrong results instead ;))

**Comment by lonvia** [comment]
We could just the increase the number of results retrieved but often this will just be a band-aid to an underlying problem. It's better to address the root cause why the results come up in a bad order. In your specific case an optional housenumber competes with an optional postcode. The housenumber wins out. This needs to be addressed. I'm converting your comment to a new issue.

**Comment by lonvia** [comment]
Secondary importance is meant to replace address importance these days. Pre-computed secondary importance is now available.
